export function createPrecisionCenterModule({state,supabase,escapeHtml,number,shortDate,openModal,loadData,render,setPage}){
  const today=()=>new Date();
  const daysSince=(d)=>d?Math.max(0,Math.floor((today()-new Date(`${d}T12:00:00`))/86400000)):null;
  const lotName=id=>state.lots.find(l=>l.id===id)?.name||'Lote';
  const latest=(arr,lotId,key)=>[...(arr||[])].filter(x=>x.lot_id===lotId).sort((a,b)=>String(b[key]||'').localeCompare(String(a[key]||'')))[0]||null;
  const vigor=(v)=>v>=.7?['Alto','good']:v>=.55?['Medio','warn']:v>0?['Bajo','bad']:['Sin datos',''];
  function lotRows(){
    return state.lots.map(l=>{
      const a=latest(state.analyses,l.id,'flight_date');
      const o=latest(state.precisionObservations,l.id,'observation_date');
      const lab=latest(state.labAnalyses,l.id,'sample_date');
      const cut=latest(state.cuts,l.id,'cut_date');
      const irrigation=latest(state.irrigations,l.id,'event_date');
      const ndvi=Number(a?.ndvi_avg||0), status=vigor(ndvi), cutDays=daysSince(cut?.cut_date), irrigDays=daysSince(irrigation?.event_date);
      const estimate=cutDays==null?'Sin historial':cutDays>=32?'Corte prioritario':cutDays>=25?'Preparar corte':`En crecimiento (${32-cutDays} días estimados)`;
      return {l,a,o,lab,cut,irrigation,ndvi,status,cutDays,irrigDays,estimate};
    }).sort((a,b)=>a.ndvi-b.ndvi);
  }
  function renderPage(){
    const rows=lotRows();
    const analyses=state.analyses||[];
    const avg=analyses.length?analyses.reduce((s,a)=>s+Number(a.ndvi_avg||0),0)/analyses.length:0;
    const low=rows.filter(r=>r.ndvi>0&&r.ndvi<.55).length;
    const observed=new Set((state.precisionObservations||[]).map(x=>x.lot_id)).size;
    const table=rows.map(r=>`<tr><td><b>${escapeHtml(r.l.name)}</b><small>${number(r.l.hectares||r.l.area_ha||0,2)} ha</small></td><td>${r.a?shortDate(r.a.flight_date):'—'}</td><td><b>${r.ndvi?number(r.ndvi,2):'—'}</b><small><span class="pill ${r.status[1]}">${r.status[0]}</span></small></td><td>${r.a?number(r.a.ndre_avg||0,2):'—'}</td><td>${r.o?escapeHtml(r.o.water_stress||'Sin definir'):'—'}</td><td>${escapeHtml(r.estimate)}</td><td><div class="actions"><button class="secondary precisionObserve" data-id="${r.l.id}">Observación</button><button class="secondary precisionLab" data-id="${r.l.id}">Laboratorio</button><button class="secondary precisionOpen" data-page="flights">Vuelos</button></div></td></tr>`).join('');
    const alerts=rows.filter(r=>(r.ndvi>0&&r.ndvi<.55)||r.irrigDays>7||r.cutDays>32).slice(0,8);
    return `<div class="page-head"><div><p class="eyebrow">AGRICULTURA DE PRECISIÓN · 17.0.0</p><h2>Inteligencia agronómica por lote</h2><p class="muted">Mavic 3 Multispectral, observaciones de campo, laboratorio, riego y producción en una sola lectura.</p></div><div class="actions"><button class="secondary precisionOpen" data-page="map">Abrir mapa</button><button class="primary precisionOpen" data-page="flights">+ Importar vuelo</button></div></div>
    <div class="metrics"><div class="metric"><span>NDVI promedio</span><b>${avg?number(avg,2):'—'}</b><small>${analyses.length} vuelos procesados</small></div><div class="metric"><span>Lotes con vigor bajo</span><b>${low}</b><small>NDVI menor a 0,55</small></div><div class="metric"><span>Recorridos de campo</span><b>${(state.precisionObservations||[]).length}</b><small>${observed} lotes observados</small></div><div class="metric"><span>Análisis de laboratorio</span><b>${(state.labAnalyses||[]).length}</b><small>suelo, agua o forraje</small></div></div>
    <div class="grid2"><section class="panel"><div class="panel-title"><div><h3>Alertas agronómicas</h3><p class="muted">Señales construidas con índices, riego y fechas productivas.</p></div></div>${alerts.length?alerts.map(r=>`<div class="row"><div><b>⚠ ${escapeHtml(r.l.name)}</b><small>${r.ndvi>0&&r.ndvi<.55?`NDVI ${number(r.ndvi,2)}. `:''}${r.irrigDays>7?`Último riego hace ${r.irrigDays} días. `:''}${r.cutDays>32?`Último corte hace ${r.cutDays} días.`:''}</small></div><button class="secondary precisionObserve" data-id="${r.l.id}">Revisar</button></div>`).join(''):'<div class="status">No hay alertas con los datos actuales.</div>'}</section>
    <section class="panel"><h3>Flujo recomendado</h3><div class="row"><div><b>1. Volar</b><small>Capturar mapa multiespectral por lote.</small></div></div><div class="row"><div><b>2. Recorrer</b><small>Validar en campo las zonas de bajo vigor.</small></div></div><div class="row"><div><b>3. Diagnosticar</b><small>Asociar análisis de suelo, agua o forraje.</small></div></div><div class="row"><div><b>4. Actuar</b><small>Generar riego, tarea u orden T100.</small></div></div></section></div>
    <div class="panel" style="margin-top:18px"><div class="panel-title"><div><h3>Estado agronómico de los lotes</h3><p class="muted">Evolución multiespectral, estrés hídrico y proyección de corte.</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Lote</th><th>Último vuelo</th><th>NDVI</th><th>NDRE</th><th>Estrés hídrico</th><th>Próximo corte</th><th></th></tr></thead><tbody>${table||'<tr><td colspan="7" class="empty">No hay lotes.</td></tr>'}</tbody></table></div></div>`;
  }
  function observationModal(lotId){
    const lot=state.lots.find(l=>l.id===lotId);openModal(`<p class="eyebrow">RECORRIDO DE CAMPO</p><h2>${escapeHtml(lot?.name||'Lote')}</h2><form id="precisionObservationForm"><input type="hidden" name="lot_id" value="${lotId}"><div class="form-grid"><label>Fecha<input type="date" name="observation_date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Estrés hídrico<select name="water_stress"><option>Bajo</option><option>Medio</option><option>Alto</option></select></label><label>Estado fenológico<input name="growth_stage" placeholder="Rebrote, botón floral..."></label><label>Cobertura estimada %<input type="number" min="0" max="100" step="1" name="canopy_cover"></label><label class="wide">Observaciones<textarea name="notes" rows="4"></textarea></label></div><button class="primary">Guardar observación</button><p id="precisionMsg" class="error hidden"></p></form>`);
    document.querySelector('#precisionObservationForm').onsubmit=saveObservation;
  }
  async function saveObservation(e){e.preventDefault();const f=new FormData(e.target);const row={company_id:state.companyId,lot_id:f.get('lot_id'),observation_date:f.get('observation_date'),water_stress:f.get('water_stress'),growth_stage:f.get('growth_stage')||null,canopy_cover:Number(f.get('canopy_cover')||0),notes:f.get('notes')||null,created_by:state.session.user.id};const {error}=await supabase.from('precision_observations').insert(row);if(error){const m=document.querySelector('#precisionMsg');m.textContent=error.message;m.classList.remove('hidden');return}document.querySelector('#modalRoot').innerHTML='';await loadData();render()}
  function labModal(lotId){const lot=state.lots.find(l=>l.id===lotId);openModal(`<p class="eyebrow">ANÁLISIS DE LABORATORIO</p><h2>${escapeHtml(lot?.name||'Lote')}</h2><form id="precisionLabForm"><input type="hidden" name="lot_id" value="${lotId}"><div class="form-grid"><label>Fecha de muestra<input type="date" name="sample_date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Tipo<select name="analysis_type"><option>Suelo</option><option>Agua</option><option>Forraje</option><option>Tejido vegetal</option></select></label><label>Laboratorio<input name="laboratory"></label><label>Resultado principal<input name="main_result" placeholder="pH 6,5 / PB 20%..."></label><label class="wide">Detalle<textarea name="results_json" rows="4" placeholder='Texto o JSON con resultados'></textarea></label></div><button class="primary">Guardar análisis</button><p id="precisionLabMsg" class="error hidden"></p></form>`);document.querySelector('#precisionLabForm').onsubmit=saveLab}
  async function saveLab(e){e.preventDefault();const f=new FormData(e.target);const row={company_id:state.companyId,lot_id:f.get('lot_id'),sample_date:f.get('sample_date'),analysis_type:f.get('analysis_type'),laboratory:f.get('laboratory')||null,main_result:f.get('main_result')||null,results_json:{detail:f.get('results_json')||''},created_by:state.session.user.id};const {error}=await supabase.from('lab_analyses').insert(row);if(error){const m=document.querySelector('#precisionLabMsg');m.textContent=error.message;m.classList.remove('hidden');return}document.querySelector('#modalRoot').innerHTML='';await loadData();render()}
  function bind(){document.querySelectorAll('.precisionOpen').forEach(b=>b.onclick=()=>setPage(b.dataset.page));document.querySelectorAll('.precisionObserve').forEach(b=>b.onclick=()=>observationModal(b.dataset.id));document.querySelectorAll('.precisionLab').forEach(b=>b.onclick=()=>labModal(b.dataset.id));}
  return {renderPage,bind};
}
