export function createEstablishmentModule({state,supabase,openModal,escapeHtml,money,number,loadData,render}){
  const today=()=>new Date().toISOString().slice(0,10);
  const byId=(arr,id)=>arr.find(x=>x.id===id);
  const pendingTasks=()=> (state.workTasks||[]).filter(x=>!['Completada','Cancelada'].includes(x.status));
  const lowStock=()=> (state.inventoryItems||[]).filter(x=>Number(x.current_stock||0)<=Number(x.minimum_stock||0));
  function renderPage(){
    const equipment=(state.equipment||[]), people=(state.personnel||[]), tasks=(state.workTasks||[]), items=(state.inventoryItems||[]);
    const activeEquipment=equipment.filter(x=>x.status==='Activo').length;
    const activePeople=people.filter(x=>x.status==='Activo').length;
    const stockValue=items.reduce((s,x)=>s+Number(x.current_stock||0)*Number(x.unit_cost||0),0);
    const overdue=tasks.filter(x=>x.due_date && x.due_date<today() && !['Completada','Cancelada'].includes(x.status));
    const taskRows=tasks.slice(0,20).map(t=>{const lot=byId(state.lots||[],t.lot_id),person=byId(people,t.personnel_id);return `<tr><td>${escapeHtml(t.due_date||'—')}</td><td><b>${escapeHtml(t.title)}</b><small>${escapeHtml(t.category||'General')}</small></td><td>${escapeHtml(lot?.name||'General')}</td><td>${escapeHtml(person?.full_name||'Sin asignar')}</td><td><span class="badge ${t.priority==='Alta'?'bad':t.priority==='Media'?'warn':''}">${escapeHtml(t.priority||'Media')}</span></td><td>${escapeHtml(t.status||'Pendiente')}</td><td><button class="secondary editWorkTask" data-id="${t.id}">Editar</button></td></tr>`}).join('');
    const stockRows=items.map(i=>`<tr><td><b>${escapeHtml(i.name)}</b><small>${escapeHtml(i.category||'Insumo')}</small></td><td>${number(i.current_stock||0,2)} ${escapeHtml(i.unit||'unidad')}</td><td>${number(i.minimum_stock||0,2)}</td><td>${money(i.unit_cost||0)}</td><td>${money(Number(i.current_stock||0)*Number(i.unit_cost||0))}</td><td><span class="badge ${Number(i.current_stock||0)<=Number(i.minimum_stock||0)?'bad':''}">${Number(i.current_stock||0)<=Number(i.minimum_stock||0)?'Reponer':'Disponible'}</span></td><td><button class="secondary editInventoryItem" data-id="${i.id}">Editar</button></td></tr>`).join('');
    return `<div class="page-head"><div><p class="eyebrow">GESTIÓN INTEGRAL DEL ESTABLECIMIENTO · 15.0.0</p><h2>Recursos, tareas e inventario</h2><p class="muted">Organizá maquinaria, personal, agenda operativa, repuestos e insumos de La Magdalena.</p></div><div class="actions"><button class="secondary newInventoryItem">+ Insumo</button><button class="primary newWorkTask">+ Tarea</button></div></div>
    <div class="stats"><div class="stat"><small>EQUIPOS ACTIVOS</small><strong>${activeEquipment}</strong><span>${equipment.length} registrados</span></div><div class="stat"><small>PERSONAL ACTIVO</small><strong>${activePeople}</strong><span>${people.length} personas</span></div><div class="stat"><small>TAREAS PENDIENTES</small><strong>${pendingTasks().length}</strong><span>${overdue.length} vencidas</span></div><div class="stat"><small>ALERTAS DE STOCK</small><strong>${lowStock().length}</strong><span>reposición necesaria</span></div><div class="stat"><small>INVENTARIO VALORIZADO</small><strong>${money(stockValue)}</strong><span>repuestos e insumos</span></div></div>
    <div class="panel"><div class="page-head"><div><p class="eyebrow">AGENDA OPERATIVA</p><h3>Trabajos y vencimientos</h3></div><button class="primary newWorkTask">+ Nueva tarea</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Fecha</th><th>Tarea</th><th>Lote</th><th>Responsable</th><th>Prioridad</th><th>Estado</th><th></th></tr></thead><tbody>${taskRows||'<tr><td colspan="7" class="empty">No hay tareas cargadas.</td></tr>'}</tbody></table></div></div>
    <div class="panel"><div class="page-head"><div><p class="eyebrow">INVENTARIO</p><h3>Repuestos e insumos</h3></div><button class="secondary newInventoryItem">+ Nuevo artículo</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Artículo</th><th>Existencia</th><th>Mínimo</th><th>Costo unitario</th><th>Valorización</th><th>Estado</th><th></th></tr></thead><tbody>${stockRows||'<tr><td colspan="7" class="empty">No hay artículos cargados.</td></tr>'}</tbody></table></div></div>`;
  }
  function taskModal(seed={}){const lots=(state.lots||[]).map(x=>`<option value="${x.id}" ${seed.lot_id===x.id?'selected':''}>${escapeHtml(x.name)}</option>`).join(''),people=(state.personnel||[]).map(x=>`<option value="${x.id}" ${seed.personnel_id===x.id?'selected':''}>${escapeHtml(x.full_name)}</option>`).join('');openModal(`<p class="eyebrow">AGENDA OPERATIVA</p><h2>${seed.id?'Editar tarea':'Nueva tarea'}</h2><form id="workTaskForm"><input type="hidden" name="id" value="${seed.id||''}"><div class="form-grid"><label>Título<input name="title" value="${escapeHtml(seed.title||'')}" required></label><label>Categoría<select name="category">${['Producción','Riego','Maquinaria','Mantenimiento','Drones','Transporte','Administración','General'].map(v=>`<option ${seed.category===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Fecha límite<input name="due_date" type="date" value="${seed.due_date||today()}" required></label><label>Prioridad<select name="priority">${['Alta','Media','Baja'].map(v=>`<option ${seed.priority===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Lote<select name="lot_id"><option value="">General</option>${lots}</select></label><label>Responsable<select name="personnel_id"><option value="">Sin asignar</option>${people}</select></label><label>Estado<select name="status">${['Pendiente','En curso','Completada','Cancelada'].map(v=>`<option ${seed.status===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="wide">Detalle<textarea name="notes">${escapeHtml(seed.notes||'')}</textarea></label></div><button class="primary">Guardar tarea</button><p id="establishmentMsg" class="error hidden"></p></form>`);document.querySelector('#workTaskForm').onsubmit=saveTask;}
  async function saveTask(e){e.preventDefault();const f=new FormData(e.target),id=f.get('id'),row={company_id:state.companyId,title:f.get('title'),category:f.get('category'),due_date:f.get('due_date'),priority:f.get('priority'),lot_id:f.get('lot_id')||null,personnel_id:f.get('personnel_id')||null,status:f.get('status'),notes:f.get('notes')};const r=id?await supabase.from('work_tasks').update(row).eq('id',id):await supabase.from('work_tasks').insert(row);if(r.error)return showError(r.error);await closeAndReload();}
  function inventoryModal(seed={}){openModal(`<p class="eyebrow">INVENTARIO DEL ESTABLECIMIENTO</p><h2>${seed.id?'Editar artículo':'Nuevo artículo'}</h2><form id="inventoryItemForm"><input type="hidden" name="id" value="${seed.id||''}"><div class="form-grid"><label>Nombre<input name="name" value="${escapeHtml(seed.name||'')}" required></label><label>Categoría<select name="category">${['Repuesto','Lubricante','Combustible','Fertilizante','Semilla','Fitosanitario','Herramienta','Otro'].map(v=>`<option ${seed.category===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Unidad<input name="unit" value="${escapeHtml(seed.unit||'unidad')}"></label><label>Stock actual<input name="current_stock" type="number" min="0" step="0.01" value="${seed.current_stock||0}"></label><label>Stock mínimo<input name="minimum_stock" type="number" min="0" step="0.01" value="${seed.minimum_stock||0}"></label><label>Costo unitario (ARS)<input name="unit_cost" type="number" min="0" step="0.01" value="${seed.unit_cost||0}"></label><label>Ubicación<input name="location" value="${escapeHtml(seed.location||'')}"></label><label>Proveedor<input name="supplier" value="${escapeHtml(seed.supplier||'')}"></label><label class="wide">Observaciones<textarea name="notes">${escapeHtml(seed.notes||'')}</textarea></label></div><button class="primary">Guardar artículo</button><p id="establishmentMsg" class="error hidden"></p></form>`);document.querySelector('#inventoryItemForm').onsubmit=saveInventory;}
  async function saveInventory(e){e.preventDefault();const f=new FormData(e.target),id=f.get('id'),row={company_id:state.companyId,name:f.get('name'),category:f.get('category'),unit:f.get('unit'),current_stock:Number(f.get('current_stock')||0),minimum_stock:Number(f.get('minimum_stock')||0),unit_cost:Number(f.get('unit_cost')||0),location:f.get('location'),supplier:f.get('supplier'),notes:f.get('notes')};const r=id?await supabase.from('inventory_items').update(row).eq('id',id):await supabase.from('inventory_items').insert(row);if(r.error)return showError(r.error);await closeAndReload();}
  function showError(error){const m=document.querySelector('#establishmentMsg');if(m){m.textContent=error.message||String(error);m.classList.remove('hidden');}}
  async function closeAndReload(){document.querySelector('#modalRoot').innerHTML='';await loadData();render();}
  function bind(){document.querySelectorAll('.newWorkTask').forEach(b=>b.onclick=()=>taskModal());document.querySelectorAll('.editWorkTask').forEach(b=>b.onclick=()=>taskModal(byId(state.workTasks||[],b.dataset.id)||{}));document.querySelectorAll('.newInventoryItem').forEach(b=>b.onclick=()=>inventoryModal());document.querySelectorAll('.editInventoryItem').forEach(b=>b.onclick=()=>inventoryModal(byId(state.inventoryItems||[],b.dataset.id)||{}));}
  return {renderPage,bind};
}
