export function createHydricIntelligenceModule({state,supabase,escapeHtml,number,loadData,render,setPage}){
  const n=v=>Number(v||0);
  const dateOnly=v=>String(v||'').slice(0,10);
  const daysBetween=(a,b=new Date())=>a?Math.max(0,Math.floor((new Date(b)-new Date(`${dateOnly(a)}T12:00:00`))/86400000)):999;
  const latestFor=(items,lotId,dateField)=>items.filter(x=>x.lot_id===lotId).sort((a,b)=>String(b[dateField]||'').localeCompare(String(a[dateField]||'')))[0];
  const avg=(arr)=>arr.length?arr.reduce((s,x)=>s+n(x),0)/arr.length:0;
  function profile(lot){return (state.hydricProfiles||[]).find(x=>x.lot_id===lot.id)||{};}
  function stationWindow(days=7){const min=Date.now()-days*86400000;return (state.weatherStationObservations||[]).filter(x=>new Date(x.observed_at||x.observation_date).getTime()>=min);}
  function dailyClimate(){
    const own=stationWindow(7);
    if(own.length){return {source:'Estación propia',eto:avg(own.map(x=>x.et0_mm)),rain:own.reduce((s,x)=>s+n(x.rain_mm),0),days:Math.max(1,own.length)};}
    const daily=state.weather?.daily;
    return {source:'Pronóstico Open-Meteo',eto:avg((daily?.et0_fao_evapotranspiration||[]).slice(0,7)),rain:(daily?.precipitation_sum||[]).slice(0,7).reduce((s,x)=>s+n(x),0),days:7};
  }
  function recommendation(lot){
    const p=profile(lot), climate=dailyClimate();
    const lastIrr=latestFor(state.irrigations||[],lot.id,'event_date')||latestFor(state.irrigations||[],lot.id,'irrigation_date');
    const lastSample=latestFor(state.gravimetricSamples||[],lot.id,'sample_date');
    const lastAnalysis=latestFor(state.analyses||[],lot.id,'flight_date');
    const lastObs=latestFor(state.precisionObservations||[],lot.id,'observation_date');
    const days=daysBetween(lastIrr?.event_date||lastIrr?.irrigation_date);
    const kc=n(p.crop_coefficient)||((lot.crop||'').toLowerCase().includes('alfalfa')?1.05:.9);
    const etoDay=n(climate.eto)||4.5;
    const effectiveRain=(n(climate.rain)/Math.max(1,n(climate.days)))*Math.min(days,7)*(n(p.rain_efficiency_pct)||80)/100;
    const irrigationMm=n(lastIrr?.millimeters||lastIrr?.mm)*((n(p.irrigation_efficiency_pct)||90)/100);
    let deficit=Math.max(0,days*etoDay*kc-effectiveRain-irrigationMm*0.15);
    let calibrationDelta=0;
    if(lastSample){
      const measured=n(lastSample.available_water_pct||lastSample.available_water_percentage);
      const trigger=n(p.refill_trigger_pct)||45;
      calibrationDelta=Math.max(-12,Math.min(18,(trigger-measured)*0.35));
      deficit=Math.max(0,deficit+calibrationDelta);
    }
    const ndvi=n(lastAnalysis?.ndvi_avg||lastObs?.ndvi);
    const ndmi=n(lastObs?.ndmi||lastAnalysis?.ndmi_avg);
    if(ndmi&&ndmi<0.2) deficit+=4;
    const application=Math.max(0,Math.min(n(p.max_application_mm)||45,deficit));
    const rate=n(p.application_rate_mm_h)||4.5;
    const hours=rate?application/rate:0;
    const sampleAge=lastSample?daysBetween(lastSample.sample_date):999;
    const dataPoints=[!!lastIrr,!!p.id,!!lastSample,!!(state.weatherStationObservations||[]).length,!!lastAnalysis||!!lastObs].filter(Boolean).length;
    let confidence=Math.min(96,55+dataPoints*8-Math.max(0,sampleAge-30)*0.25);
    confidence=Math.max(35,Math.round(confidence));
    let status='Correcto',css='';
    if(application>=25){status='Regar hoy';css='bad';}
    else if(application>=15){status='Regar en 24 h';css='warn';}
    else if(application>=7){status='Vigilar 48 h';css='warn';}
    const nextSample=sampleAge>45?'Tomar muestra ahora':sampleAge>30?'Dentro de 7 días':sampleAge===999?'Calibración inicial':'No necesaria todavía';
    return {lot,p,lastIrr,lastSample,lastAnalysis,lastObs,days,etoDay,effectiveRain,irrigationMm,deficit,application,hours,confidence,status,css,nextSample,source:climate.source,ndvi,ndmi,calibrationDelta};
  }
  function renderPage(){
    const cards=(state.lots||[]).map(recommendation).sort((a,b)=>b.application-a.application);
    const urgent=cards.filter(x=>x.application>=25).length;
    const soon=cards.filter(x=>x.application>=7&&x.application<25).length;
    const calibrated=cards.filter(x=>x.lastSample&&daysBetween(x.lastSample.sample_date)<=45).length;
    const own=(state.weatherStationObservations||[]).length;
    return `<div class="page-head"><div><p class="eyebrow">INTELIGENCIA HÍDRICA 19.0</p><h2>Riego predictivo y calibración gravimétrica</h2><p class="muted">Estimación diaria con estación propia, balance hídrico, riegos, Mavic, satélite y verificaciones periódicas de humedad.</p></div><div class="actions"><button class="secondary hydricStation">Cargar clima</button><button class="primary hydricSample">Cargar muestra</button></div></div>
    <div class="metrics"><div class="metric"><span>Regar hoy</span><b>${urgent}</b><small>lotes prioritarios</small></div><div class="metric"><span>Próximas 48 h</span><b>${soon}</b><small>lotes en vigilancia</small></div><div class="metric"><span>Modelo calibrado</span><b>${calibrated}/${cards.length}</b><small>muestra de los últimos 45 días</small></div><div class="metric"><span>Datos estación</span><b>${own}</b><small>registros propios</small></div></div>
    <div class="panel"><div class="panel-title"><div><h3>Prioridad de riego por lote</h3><p class="muted">La lámina sugerida es orientativa hasta completar el perfil de suelo y una calibración inicial.</p></div><button class="secondary hydricExport">Exportar CSV</button></div>
    ${cards.map(x=>`<article class="analysis-card" style="margin-top:12px"><div class="panel-title"><div><b>${escapeHtml(x.lot.name)}</b><small>${escapeHtml(x.lot.crop||'Sin cultivo')} · ${number(x.lot.hectares||x.lot.area_ha,2)} ha</small></div><span class="pill ${x.css}">${x.status}</span></div><div class="grid3"><div><span class="muted">Lámina sugerida</span><b class="big">${number(x.application,1)} mm</b></div><div><span class="muted">Tiempo estimado</span><b class="big">${number(x.hours,1)} h</b></div><div><span class="muted">Confianza</span><b class="big">${x.confidence}%</b></div></div><div class="row"><span>ET₀ usada</span><b>${number(x.etoDay,1)} mm/día · ${escapeHtml(x.source)}</b></div><div class="row"><span>Último riego</span><b>${x.lastIrr?`${x.days} días · ${number(x.lastIrr.millimeters||x.lastIrr.mm,1)} mm`:'Sin registrar'}</b></div><div class="row"><span>Última gravimetría</span><b>${x.lastSample?`${escapeHtml(dateOnly(x.lastSample.sample_date))} · ${number(x.lastSample.gravimetric_moisture_pct,1)}%`:'Sin calibrar'}</b></div><div class="row"><span>Próxima verificación</span><b>${escapeHtml(x.nextSample)}</b></div><div class="row"><span>Teledetección</span><b>${x.ndvi?`NDVI ${number(x.ndvi,2)}`:'sin NDVI'}${x.ndmi?` · NDMI ${number(x.ndmi,2)}`:''}</b></div><div class="actions" style="margin-top:12px"><button class="secondary hydricProfile" data-lot="${x.lot.id}">Configurar lote</button><button class="secondary hydricSample" data-lot="${x.lot.id}">Nueva muestra</button><button class="secondary hydricGo" data-page="irrigation">Registrar riego</button></div></article>`).join('')||'<p class="empty">Primero cargá los lotes.</p>'}</div>
    <div class="grid2" style="margin-top:18px"><div class="panel"><h3>Cómo aprende el modelo</h3><p>La aplicación calcula diariamente el consumo y compara periódicamente su estimación con la humedad gravimétrica medida. Cuando encuentra desvíos, corrige el balance del lote sin exigir muestreos frecuentes.</p><div class="status"><b>Frecuencia inicial sugerida:</b> una muestra por ambiente cada 15–30 días y después de eventos excepcionales. Al estabilizarse el error, la frecuencia puede espaciarse.</div></div><div class="panel"><h3>Fuentes integradas</h3><div class="row"><span>Estación meteorológica propia</span><span class="pill ${own?'':'warn'}">${own?'Con datos':'Pendiente'}</span></div><div class="row"><span>Humedad gravimétrica</span><span class="pill ${(state.gravimetricSamples||[]).length?'':'warn'}">${(state.gravimetricSamples||[]).length?'Activa':'Pendiente'}</span></div><div class="row"><span>Mavic 3 Multiespectral</span><span class="pill ${(state.analyses||[]).length?'':'warn'}">${(state.analyses||[]).length?'Con vuelos':'Sin vuelos'}</span></div><div class="row"><span>Imágenes satelitales</span><span class="pill ${(state.precisionObservations||[]).some(x=>String(x.source||'').toLowerCase().includes('sat'))?'':'warn'}">${(state.precisionObservations||[]).some(x=>String(x.source||'').toLowerCase().includes('sat'))?'Conectadas':'Preparado'}</span></div></div></div>`;
  }
  function overlay(html){let root=document.querySelector('#hydricModal');if(!root){root=document.createElement('div');root.id='hydricModal';document.body.appendChild(root);}root.innerHTML=`<div class="modal-backdrop"><div class="modal"><button class="close hydricClose">×</button>${html}</div></div>`;root.querySelector('.hydricClose').onclick=()=>root.remove();}
  function sampleForm(lotId=''){
    overlay(`<p class="eyebrow">CALIBRACIÓN</p><h2>Nueva muestra gravimétrica</h2><form id="hydricSampleForm"><div class="form-grid"><label>Lote<select name="lot_id" required>${(state.lots||[]).map(l=>`<option value="${l.id}" ${l.id===lotId?'selected':''}>${escapeHtml(l.name)}</option>`).join('')}</select></label><label>Fecha<input type="date" name="sample_date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Profundidad inicial (cm)<input type="number" name="depth_from_cm" value="0"></label><label>Profundidad final (cm)<input type="number" name="depth_to_cm" value="40"></label><label>Humedad gravimétrica (%)<input type="number" step="0.01" name="gravimetric_moisture_pct" required></label><label>Agua disponible estimada (%)<input type="number" step="0.1" name="available_water_pct"></label><label class="wide">Observaciones<textarea name="notes"></textarea></label></div><button class="primary">Guardar calibración</button><p id="hydricMsg" class="error hidden"></p></form>`);
    document.querySelector('#hydricSampleForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const payload=Object.fromEntries(f);payload.company_id=state.companyId;['depth_from_cm','depth_to_cm','gravimetric_moisture_pct','available_water_pct'].forEach(k=>payload[k]=payload[k]===''?null:n(payload[k]));const {error}=await supabase.from('gravimetric_samples').insert(payload);if(error){const m=document.querySelector('#hydricMsg');m.textContent=error.message;m.classList.remove('hidden');return;}document.querySelector('#hydricModal')?.remove();await loadData();render();};
  }
  function stationForm(){overlay(`<p class="eyebrow">ESTACIÓN PROPIA</p><h2>Cargar observación meteorológica</h2><form id="hydricStationForm"><div class="form-grid"><label>Fecha y hora<input type="datetime-local" name="observed_at" value="${new Date().toISOString().slice(0,16)}" required></label><label>Lluvia (mm)<input type="number" step="0.1" name="rain_mm" value="0"></label><label>ET₀ (mm)<input type="number" step="0.01" name="et0_mm"></label><label>Temperatura media (°C)<input type="number" step="0.1" name="temperature_avg_c"></label><label>Humedad relativa (%)<input type="number" step="0.1" name="relative_humidity_pct"></label><label>Viento medio (km/h)<input type="number" step="0.1" name="wind_speed_kmh"></label><label>Radiación (MJ/m²)<input type="number" step="0.01" name="solar_radiation_mj_m2"></label><label class="wide">Fuente / archivo<input name="source_reference" placeholder="Consola, CSV, API..."></label></div><button class="primary">Guardar dato</button><p id="hydricMsg" class="error hidden"></p></form>`);document.querySelector('#hydricStationForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),payload=Object.fromEntries(f);payload.company_id=state.companyId;['rain_mm','et0_mm','temperature_avg_c','relative_humidity_pct','wind_speed_kmh','solar_radiation_mj_m2'].forEach(k=>payload[k]=payload[k]===''?null:n(payload[k]));const {error}=await supabase.from('weather_station_observations').insert(payload);if(error){const m=document.querySelector('#hydricMsg');m.textContent=error.message;m.classList.remove('hidden');return;}document.querySelector('#hydricModal')?.remove();await loadData();render();};}
  function profileForm(lotId){const lot=(state.lots||[]).find(x=>x.id===lotId),p=profile(lot||{});overlay(`<p class="eyebrow">PERFIL HÍDRICO</p><h2>${escapeHtml(lot?.name||'Lote')}</h2><form id="hydricProfileForm"><input type="hidden" name="lot_id" value="${lotId}"><div class="form-grid"><label>Capacidad de campo (%)<input type="number" step="0.1" name="field_capacity_pct" value="${p.field_capacity_pct??''}"></label><label>Punto de marchitez (%)<input type="number" step="0.1" name="wilting_point_pct" value="${p.wilting_point_pct??''}"></label><label>Profundidad radicular (cm)<input type="number" name="root_depth_cm" value="${p.root_depth_cm??60}"></label><label>Umbral para regar (% agua disponible)<input type="number" step="0.1" name="refill_trigger_pct" value="${p.refill_trigger_pct??45}"></label><label>Eficiencia del riego (%)<input type="number" step="0.1" name="irrigation_efficiency_pct" value="${p.irrigation_efficiency_pct??90}"></label><label>Precipitación del sistema (mm/h)<input type="number" step="0.01" name="application_rate_mm_h" value="${p.application_rate_mm_h??4.5}"></label><label>Coeficiente Kc<input type="number" step="0.01" name="crop_coefficient" value="${p.crop_coefficient??1.05}"></label><label>Lámina máxima por turno (mm)<input type="number" step="0.1" name="max_application_mm" value="${p.max_application_mm??45}"></label></div><button class="primary">Guardar perfil</button><p id="hydricMsg" class="error hidden"></p></form>`);document.querySelector('#hydricProfileForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),payload=Object.fromEntries(f);payload.company_id=state.companyId;Object.keys(payload).filter(k=>!['company_id','lot_id'].includes(k)).forEach(k=>payload[k]=payload[k]===''?null:n(payload[k]));const {error}=await supabase.from('hydric_profiles').upsert(payload,{onConflict:'company_id,lot_id'});if(error){const m=document.querySelector('#hydricMsg');m.textContent=error.message;m.classList.remove('hidden');return;}document.querySelector('#hydricModal')?.remove();await loadData();render();};}
  function exportCsv(){const rows=[['Lote','Estado','Lámina mm','Horas','Confianza %','Próxima muestra'],...(state.lots||[]).map(l=>{const x=recommendation(l);return [l.name,x.status,x.application.toFixed(1),x.hours.toFixed(1),x.confidence,x.nextSample];})];const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='LA_MAGDALENA_OS_19_RIEGO.csv';a.click();URL.revokeObjectURL(a.href);}
  function bind(){document.querySelectorAll('.hydricSample').forEach(b=>b.onclick=()=>sampleForm(b.dataset.lot||''));document.querySelectorAll('.hydricStation').forEach(b=>b.onclick=stationForm);document.querySelectorAll('.hydricProfile').forEach(b=>b.onclick=()=>profileForm(b.dataset.lot));document.querySelectorAll('.hydricGo').forEach(b=>b.onclick=()=>setPage(b.dataset.page));const ex=document.querySelector('.hydricExport');if(ex)ex.onclick=exportCsv;}
  return {renderPage,bind};
}
