import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'
import { createLotsModule } from './modules/lots.js'
import { createProductionModule } from './modules/production/index.js'
import { createGisModule } from './modules/gis/index.js'
import { createTransportModule } from './modules/transport/index.js'
import { createOperationsModule } from './modules/operations/index.js'
import { createSalesModule } from './modules/sales/index.js'
import { createPurchasesModule } from './modules/purchases/index.js'
import { createFinanceModule } from './modules/finance/index.js'
import { createDataSafetyModule } from './modules/data-safety/index.js'
import { createResourcesModule } from './modules/resources/index.js'
import { createCampaignsModule } from './modules/campaigns/index.js'
const sb=createClient('https://grlifamrkdoffglvrttu.supabase.co','sb_publishable_NlFza1aVKzhWh2Xiwm0VGQ_wI1aPdTN')
const APP_VERSION='13.0.0';
const APP_RELEASE='Gestión integral de campaña';
const S={session:null,companies:[],companyId:'',lots:[],geometries:[],analyses:[],orders:[],clients:[],irrigations:[],cuts:[],trips:[],movements:[],equipment:[],fuelEntries:[],maintenanceEntries:[],personnel:[],laborEntries:[],salesOrders:[],salesItems:[],salesPayments:[],stockMovements:[],campaigns:[],selectedCampaignId:'',modules:[],members:[],invitations:[],membership:null,weather:null,page:'operations',map:null,drawn:null,selectedLotId:''};const $=s=>document.querySelector(s);const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function applyReleaseIdentity(){
  document.title=`LA MAGDALENA OS · ${APP_VERSION} · ${APP_RELEASE}`;
  const eyebrow=document.querySelector('.top .eyebrow');
  if(eyebrow) eyebrow.textContent=`LA MAGDALENA OS · ${APP_VERSION}`;
  const brand=document.querySelector('.brand small');
  if(brand) brand.textContent=`OS · ${APP_VERSION} · OPERATIVO`;
}
async function init(){applyReleaseIdentity();const {data}=await sb.auth.getSession();if(data.session)await showApp(data.session);sb.auth.onAuthStateChange(async(_e,s)=>s?showApp(s):showLogin())}
function showLogin(){$('#login').classList.remove('hidden');$('#app').classList.add('hidden')}
async function showApp(session){
  S.session=session;
  $('#login').classList.add('hidden');
  $('#app').classList.remove('hidden');
  $('#content').innerHTML='<div class="panel"><h2>Cargando dashboard…</h2><p class="muted">Conectando con la base de datos.</p></div>';
  try{
    await sb.rpc('claim_company_invitations').catch?.(()=>{});
    await loadCompanies();
    await loadData();
    render();
    loadWeather().then(()=>{ if(S.page==='dashboard'||S.page==='weather') render(); }).catch(console.warn);
  }catch(err){
    console.error(err);
    $('#content').innerHTML=`<div class="panel"><h2>No se pudo cargar el dashboard</h2><p class="error">${esc(err?.message||err)}</p><button id="retryLoad" class="primary">Reintentar</button></div>`;
    const retry=$('#retryLoad'); if(retry) retry.onclick=()=>showApp(session);
  }
}
$('#signupBtn').onclick=async()=>{const m=$('#loginMsg'),email=$('#email').value.trim(),password=$('#password').value;m.classList.add('hidden');if(!email||password.length<6){m.textContent='Ingresá un correo y una contraseña de al menos 6 caracteres.';m.classList.remove('hidden');return}const {error}=await sb.auth.signUp({email,password,options:{data:{full_name:'Franco Luciano Bodio'}}});m.textContent=error?error.message:'Cuenta creada. Si Supabase solicita confirmación, revisá tu correo.';m.classList.remove('hidden')};
$('#resetBtn').onclick=async()=>{const m=$('#loginMsg'),email=$('#email').value.trim();m.classList.add('hidden');if(!email){m.textContent='Ingresá tu correo primero.';m.classList.remove('hidden');return}const {error}=await sb.auth.resetPasswordForEmail(email);m.textContent=error?error.message:'Se envió el enlace de recuperación al correo.';m.classList.remove('hidden')};
$('#logout').onclick=()=>sb.auth.signOut();$('#menuBtn').onclick=()=>$('#side').classList.toggle('open');$('#nav').onclick=e=>{const b=e.target.closest('button[data-page]');if(!b)return;S.page=b.dataset.page;document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===b));$('#side').classList.remove('open');render()};$('#companySelect').onchange=async e=>{S.companyId=e.target.value;await loadData();await loadWeather();render()}
async function loadCompanies(){const {data,error}=await sb.from('companies').select('*').order('name');if(error)throw error;S.companies=data||[];S.companyId=S.companyId||S.companies[0]?.id||'';$('#companySelect').innerHTML=S.companies.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');$('#companySelect').value=S.companyId}
async function safeTable(name,order){let q=sb.from(name).select('*').eq('company_id',S.companyId);if(order)q=q.order(order,{ascending:false});const r=await q;return r.error?[]:(r.data||[])}
async function loadData(){if(!S.companyId)return;const [a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v]=await Promise.all([safeTable('lots','name'),safeTable('lot_geometries'),safeTable('precision_analyses','flight_date'),safeTable('precision_orders','order_date'),safeTable('clients','created_at'),safeTable('irrigation_events','event_date'),safeTable('alfalfa_cuts','cut_date'),safeTable('transport_trips','trip_date'),safeTable('financial_movements','movement_date'),safeTable('company_modules','module_key'),safeTable('company_members','created_at'),safeTable('company_invitations','created_at'),safeTable('equipment','name'),safeTable('fuel_entries','entry_date'),safeTable('maintenance_entries','service_date'),safeTable('personnel','full_name'),safeTable('labor_entries','work_date'),safeTable('sales_orders','sale_date'),safeTable('sales_order_items','created_at'),safeTable('sales_payments','payment_date'),safeTable('alfalfa_stock_movements','movement_date'),safeTable('campaigns','start_date')]);S.lots=a;S.geometries=b;S.analyses=c;S.orders=d;S.clients=e;S.irrigations=f;S.cuts=g;S.trips=h;S.movements=i;S.modules=j;S.members=k;S.invitations=l;S.equipment=m;S.fuelEntries=n;S.maintenanceEntries=o;S.personnel=p;S.laborEntries=q;S.salesOrders=r;S.salesItems=s;S.salesPayments=t;S.stockMovements=u;S.campaigns=v;S.membership=S.members.find(m=>m.user_id===S.session?.user?.id)||null;applyRoleAccess()}
async function loadWeather(){try{const c=S.companies.find(x=>x.id===S.companyId)||{};const lat=Number(c.latitude||-31.332065),lng=Number(c.longitude||-63.311986);const url=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lng}&current=temperature_2m,relative_humidity_2m,wind_speed_10m,wind_direction_10m,weather_code&hourly=temperature_2m,relative_humidity_2m,precipitation_probability,precipitation,wind_speed_10m,et0_fao_evapotranspiration&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum,precipitation_probability_max,et0_fao_evapotranspiration&timezone=America%2FArgentina%2FCordoba&forecast_days=7`;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),8000);const r=await fetch(url,{signal:controller.signal});clearTimeout(timer);if(!r.ok)throw new Error('Clima no disponible');S.weather=await r.json()}catch(e){console.warn(e);S.weather=null}}
const weatherText=code=>({0:'Despejado',1:'Mayormente despejado',2:'Parcialmente nublado',3:'Nublado',45:'Niebla',48:'Niebla con escarcha',51:'Llovizna leve',53:'Llovizna',55:'Llovizna intensa',61:'Lluvia leve',63:'Lluvia',65:'Lluvia intensa',71:'Nieve leve',80:'Chaparrones',81:'Chaparrones',82:'Chaparrones fuertes',95:'Tormenta'}[code]||'Variable');
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(n||0));
const number=(n,digits=0)=>new Intl.NumberFormat('es-AR',{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(Number(n||0));
const hectares=n=>`${number(n,2)} ha`;
const shortDate=value=>value?new Intl.DateTimeFormat('es-AR',{day:'2-digit',month:'short'}).format(new Date(`${String(value).slice(0,10)}T12:00:00`)):'Sin registrar';
const latest=l=>S.analyses.find(a=>a.lot_id===l.id);const previous=l=>S.analyses.filter(a=>a.lot_id===l.id)[1];const vigor=v=>v==null?['Sin datos','warn']:v<.45?['Bajo','bad']:v<.62?['Medio','warn']:v<.78?['Bueno','']:['Muy alto',''];const totalHa=()=>S.lots.reduce((s,x)=>s+Number(x.hectares||x.area_ha||0),0);const avgNdvi=()=>{const a=S.analyses.filter(x=>x.ndvi_avg!=null);return a.length?a.reduce((s,x)=>s+Number(x.ndvi_avg),0)/a.length:0}

const rolePages={
  Superadministrador:['saas','data-safety','operations','dashboard','management','weather','production','map','irrigation','flights','orders','lots','clients','sales','purchases','finance','transport','resources','campaigns','admin','ai','portal'],
  Administrador:['saas','data-safety','operations','dashboard','management','weather','production','map','irrigation','flights','orders','lots','clients','sales','purchases','finance','transport','resources','campaigns','admin','ai','portal'],
  Encargado:['operations','dashboard','management','weather','production','alfalfa','map','irrigation','flights','orders','lots','clients','sales','purchases','finance','transport','resources','campaigns','admin','ai','portal'],
  Operario:['operations','dashboard','weather','production','alfalfa','map','irrigation','flights','orders','lots','transport','ai'],
  Asesor:['operations','dashboard','management','weather','alfalfa','map','flights','lots','ai','portal'],
  Cliente:['operations','dashboard','weather','lots','portal']
};
const currentRole=()=>S.membership?.role||'Cliente';
const canOpenPage=page=>(rolePages[currentRole()]||rolePages.Cliente).includes(page);
function applyRoleAccess(){
  document.querySelectorAll('#nav button[data-page]').forEach(b=>b.classList.toggle('hidden',!canOpenPage(b.dataset.page)));
  const account=document.querySelector('.account');
  if(account){const name=S.membership?.full_name||S.session?.user?.user_metadata?.full_name||S.session?.user?.email||'Usuario';account.querySelector('b').textContent=name;account.querySelector('small').textContent=currentRole();}
  if(!canOpenPage(S.page))S.page='dashboard';
}

const planLabel=p=>({basic:'Básico',professional:'Profesional',premium:'Premium',enterprise:'Enterprise'}[p]||p||'Sin plan');
function render(){try{if(!canOpenPage(S.page)){S.page='dashboard';applyRoleAccess();}const titles={saas:'Centro SaaS','data-safety':'Seguridad de datos',operations:'Centro operativo',dashboard:'Dashboard',management:'Tablero gerencial',weather:'Centro meteorológico',production:'Producción',alfalfa:'Centro Alfalfa',map:'Precisión y mapa',irrigation:'Riego inteligente',flights:'Vuelos y análisis',orders:'Órdenes T100',lots:'Lotes',clients:'Clientes',sales:'Ventas y cobranzas',purchases:'Compras y proveedores',finance:'Flujo de fondos',transport:'Transporte',resources:'Recursos operativos',campaigns:'Campañas',admin:'Administración',ai:'LM AI',portal:'Portal de clientes'};$('#pageTitle').textContent=titles[S.page];$('#content').innerHTML=({saas:saasPage,'data-safety':dataSafetyModule.renderPage,operations:operationsModule.renderPage,dashboard:dashboardPage,management:managementPage,weather:weatherPage,production:productionModule.renderPage,alfalfa:alfalfaDecisionPage,map:gisModule.renderPage,irrigation:irrigationPage,flights:flightsPage,orders:ordersPage,lots:lotsModule.renderPage,clients:clientsPage,sales:salesModule.renderPage,purchases:purchasesModule.renderPage,finance:financeModule.renderPage,transport:transportModule.renderPage,resources:resourcesModule.renderPage,campaigns:campaignsModule.renderPage,admin:adminPage,ai:aiPage,portal:portalPage}[S.page])();bind();if(S.page==='map')setTimeout(gisModule.initMap,50)}catch(err){console.error(err);$('#content').innerHTML=`<div class="panel"><h2>Error al mostrar ${esc(S.page)}</h2><p class="error">${esc(err?.message||err)}</p></div>`}}

function parseCutDecision(cut){
  try{
    const raw=String(cut.notes||'');
    const meta=raw.startsWith('LMOS_CUT:')?JSON.parse(raw.slice(9)):{};
    const rolls=Number(cut.bales||cut.rolls||0),weight=Number(meta.weight||500),sold=Number(meta.sold_rolls||0);
    const costs=['fuel_cost','tractor_cost','mower_cost','rake_cost','baler_cost','labor_cost','machinery_cost','freight_cost','repairs_cost','other_cost'].reduce((sum,k)=>sum+Number(meta[k]||0),0);
    const revenue=sold*Number(meta.sale_price_per_roll||0)+(Number(meta.sale_price_per_ton||0)>0?Math.max(0,(rolls-sold)*weight/1000)*Number(meta.sale_price_per_ton||0):0);
    return {...cut,meta,rolls,weight,sold,stock:Math.max(0,rolls-sold),tons:rolls*weight/1000,costs,revenue,margin:revenue-costs};
  }catch(_e){return {...cut,meta:{},rolls:Number(cut.bales||cut.rolls||0),weight:500,sold:0,stock:Number(cut.bales||cut.rolls||0),tons:Number(cut.total_kg||0)/1000,costs:0,revenue:0,margin:0}}
}
function alfalfaDecisionPage(){
  const cuts=S.cuts.map(parseCutDecision).sort((a,b)=>String(b.cut_date||'').localeCompare(String(a.cut_date||'')));
  const alfalfaLots=S.lots.filter(l=>String(l.crop||'').toLowerCase().includes('alfalfa'));
  const totalRolls=cuts.reduce((n,c)=>n+c.rolls,0),stock=cuts.reduce((n,c)=>n+c.stock,0),tons=cuts.reduce((n,c)=>n+c.tons,0);
  const costs=cuts.reduce((n,c)=>n+c.costs,0),revenue=cuts.reduce((n,c)=>n+c.revenue,0),margin=revenue-costs;
  const today=Date.now();
  const plans=alfalfaLots.map(l=>{
    const lotCuts=cuts.filter(c=>c.lot_id===l.id);
    const last=lotCuts[0];
    const days=last?.cut_date?Math.max(0,Math.floor((today-new Date(last.cut_date+'T12:00:00').getTime())/86400000)):999;
    const due=days>=32?'Cortar ahora':days>=26?'Preparar corte':days>=20?'Monitorear':'En crecimiento';
    const score=days>=32?4:days>=26?3:days>=20?2:1;
    const nd=latest(l);
    return {l,last,days,due,score,ndvi:Number(nd?.ndvi_avg||0)};
  }).sort((a,b)=>b.score-a.score||b.days-a.days);
  const alerts=[];
  plans.filter(x=>x.days>=32).forEach(x=>alerts.push(`${x.l.name}: ${x.days} días desde el último corte.`));
  cuts.filter(c=>Number(c.meta.humidity||0)>20).slice(0,4).forEach(c=>alerts.push(`${S.lots.find(l=>l.id===c.lot_id)?.name||'Lote'}: humedad ${number(c.meta.humidity,1)}%, revisar almacenamiento.`));
  cuts.filter(c=>c.margin<0&&c.revenue>0).slice(0,4).forEach(c=>alerts.push(`${S.lots.find(l=>l.id===c.lot_id)?.name||'Lote'}: margen negativo en el corte del ${shortDate(c.cut_date)}.`));
  const planRows=plans.map(x=>`<tr><td><b>${esc(x.l.name)}</b><small>${hectares(x.l.hectares||x.l.area_ha)}</small></td><td>${x.last?shortDate(x.last.cut_date):'Sin registrar'}</td><td>${x.last?`${x.days} días`:'—'}</td><td>${x.ndvi?number(x.ndvi,2):'—'}</td><td><span class="pill ${x.score>=4?'bad':x.score>=3?'warn':''}">${x.due}</span></td><td><button class="secondary goProduction">Abrir producción</button></td></tr>`).join('');
  const recent=cuts.slice(0,8).map(c=>`<tr><td>${shortDate(c.cut_date)}</td><td><b>${esc(S.lots.find(l=>l.id===c.lot_id)?.name||'Lote')}</b></td><td>${number(c.rolls)} rollos<small>${number(c.tons,1)} t</small></td><td>${number(c.stock)} rollos</td><td>${money(c.costs)}</td><td class="${c.margin>=0?'positive':'negative'}">${money(c.margin)}</td></tr>`).join('');
  return `<div class="page-head"><div><p class="eyebrow">GESTIÓN DE ALFALFA 5.0</p><h2>Alfalfa: producción, stock y próximos cortes</h2><p class="muted">Prioridades automáticas construidas con los datos ya registrados en cada lote y corte.</p></div><button class="primary newCut">+ Registrar corte</button></div>
  <div class="metrics"><div class="metric"><span>Producción acumulada</span><b>${number(totalRolls)} rollos</b><small>${number(tons,1)} toneladas</small></div><div class="metric"><span>Stock estimado</span><b>${number(stock)} rollos</b><small>producidos menos vendidos</small></div><div class="metric"><span>Costo acumulado</span><b>${money(costs)}</b><small>${totalRolls?money(costs/totalRolls):money(0)} por rollo</small></div><div class="metric"><span>Margen registrado</span><b>${money(margin)}</b><small>Ingresos ${money(revenue)}</small></div></div>
  <div class="grid2"><div class="panel"><div class="panel-title"><div><h3>Planificador de cortes</h3><p class="muted">Ventana orientativa: preparar desde 26 días y priorizar desde 32 días.</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Lote</th><th>Último corte</th><th>Días</th><th>NDVI</th><th>Decisión</th><th></th></tr></thead><tbody>${planRows||'<tr><td colspan="6" class="empty">No hay lotes de alfalfa.</td></tr>'}</tbody></table></div></div><div class="panel"><h3>Alertas de gestión</h3>${alerts.length?alerts.slice(0,10).map(a=>`<div class="row"><div><b>⚠ ${esc(a)}</b></div></div>`).join(''):'<div class="status">No hay alertas automáticas con los datos actuales.</div>'}<div class="status" style="margin-top:14px"><b>Recomendación LM AI</b><br>${plans[0]?`${esc(plans[0].l.name)} es la prioridad actual: ${esc(plans[0].due.toLowerCase())}. Confirmar estado del cultivo, humedad y pronóstico antes de operar.`:'Cargá cortes para generar prioridades automáticas.'}</div></div></div>
  <div class="panel" style="margin-top:18px"><div class="panel-title"><div><h3>Resultado por corte</h3><p class="muted">Producción, stock y margen según los datos cargados.</p></div><button class="secondary goProduction">Ver módulo completo</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Fecha</th><th>Lote</th><th>Producción</th><th>Stock</th><th>Costos</th><th>Margen</th></tr></thead><tbody>${recent||'<tr><td colspan="6" class="empty">Todavía no hay cortes registrados.</td></tr>'}</tbody></table></div></div>`;
}
function flightsPage(){
  const analyses=[...S.analyses].sort((a,b)=>String(b.flight_date||'').localeCompare(String(a.flight_date||'')));
  const analysedLots=new Set(analyses.map(a=>a.lot_id)).size;
  const average=analyses.length?analyses.reduce((sum,a)=>sum+Number(a.ndvi_avg||0),0)/analyses.length:0;
  const lowVigor=analyses.filter(a=>Number(a.low_vigor_pct||0)>15).length;
  const cards=analyses.map(a=>{
    const lot=S.lots.find(l=>l.id===a.lot_id);
    const history=analyses.filter(x=>x.lot_id===a.lot_id);
    const position=history.findIndex(x=>x.id===a.id);
    const prior=position>=0?history[position+1]:null;
    const delta=prior?Number(a.ndvi_avg||0)-Number(prior.ndvi_avg||0):null;
    const v=vigor(a.ndvi_avg);
    return `<article class="analysis-card"><div class="panel-title"><div><b>${esc(lot?.name||'Lote sin identificar')}</b><small class="muted">${shortDate(a.flight_date)} · ${hectares(a.hectares||lot?.hectares||0)}</small></div><span class="pill ${v[1]}">${v[0]}</span></div><span>NDVI promedio</span><b class="big">${number(a.ndvi_avg,2)}</b><div class="progress"><i style="width:${Math.max(0,Math.min(100,Number(a.ndvi_avg||0)*100))}%"></i></div><p>NDRE ${number(a.ndre_avg,2)} · Bajo vigor ${number(a.low_vigor_pct,1)}%</p><p class="muted">${delta==null?'Primer análisis del lote':`Cambio vs. vuelo anterior: ${delta>=0?'+':''}${number(delta,2)}`}</p><p>${esc(a.recommendation||'Sin recomendación registrada.')}</p><div class="actions"><button class="secondary makeOrder" data-id="${a.id}">Crear orden T100</button><button class="secondary openFile" data-path="${esc(a.map_file_path||'')}">Abrir mapa</button></div></article>`;
  }).join('');
  return `<div class="page-head"><div><p class="eyebrow">DJI MAVIC 3 MULTISPECTRAL</p><h2>Vuelos y análisis</h2><p class="muted">Historial multiespectral, vigor por lote y generación de órdenes de aplicación.</p></div><button class="primary newAnalysis">+ Importar análisis</button></div><div class="metrics"><div class="metric"><span>Vuelos procesados</span><b>${number(analyses.length)}</b><small>análisis guardados</small></div><div class="metric"><span>Lotes analizados</span><b>${number(analysedLots)}</b><small>de ${number(S.lots.length)} lotes</small></div><div class="metric"><span>NDVI promedio</span><b>${analyses.length?number(average,2):'—'}</b><small>promedio histórico</small></div><div class="metric"><span>Requieren revisión</span><b>${number(lowVigor)}</b><small>más de 15% de bajo vigor</small></div></div><div class="grid3">${cards||'<div class="panel empty"><h3>Todavía no hay vuelos procesados</h3><p>Importá un CSV de zonas para calcular NDVI, NDRE y porcentaje de bajo vigor.</p><button class="primary newAnalysis">Importar primer análisis</button></div>'}</div>`;
}

function ordersPage(){
  const rows=[...S.orders].sort((a,b)=>String(b.order_date||'').localeCompare(String(a.order_date||''))).map(o=>`<tr><td>${shortDate(o.order_date)}</td><td><b>${esc(o.lot_name||S.lots.find(l=>l.id===o.lot_id)?.name||'Lote')}</b></td><td>${esc(o.application_type||'Aplicación')}</td><td>${hectares(o.hectares||0)}</td><td>${esc(o.product||'—')} · ${number(o.dose,2)} ${esc(o.dose_unit||'')}</td><td>${number(o.estimated_product,1)} producto · ${number(o.estimated_batteries)} bat. · ${number(o.estimated_minutes)} min</td><td><span class="pill">${esc(o.status||'Planificada')}</span></td></tr>`).join('');
  return `<div class="page-head"><div><p class="eyebrow">DJI AGRAS T100</p><h2>Órdenes de aplicación</h2><p class="muted">Planificación y seguimiento de aplicaciones vinculadas con cada lote.</p></div><button class="primary newOrder">+ Nueva orden</button></div><div class="panel"><table class="table"><thead><tr><th>Fecha</th><th>Lote</th><th>Trabajo</th><th>Superficie</th><th>Producto</th><th>Estimación</th><th>Estado</th></tr></thead><tbody>${rows||'<tr><td colspan="7" class="muted">No hay órdenes registradas.</td></tr>'}</tbody></table></div>`;
}

function dashboardPage(){
  const activeLots=S.lots.filter(l=>String(l.status||'Activo').toLowerCase()!=='archivado');
  const alerts=activeLots.filter(l=>latest(l)?.ndvi_avg!=null&&Number(latest(l).ndvi_avg)<.62).length;
  const w=S.weather?.current;
  const weather=w?`${weatherText(w.weather_code)} · ${number(w.temperature_2m,1)} °C · viento ${number(w.wind_speed_10m)} km/h`:'Clima sin conexión';
  const cropSummary=Object.entries(activeLots.reduce((acc,l)=>{const crop=String(l.crop||'Sin cultivo').trim()||'Sin cultivo';acc[crop]=(acc[crop]||0)+Number(l.hectares||l.area_ha||0);return acc},{})).sort((a,b)=>b[1]-a[1]);
  const rolls=S.cuts.reduce((sum,x)=>sum+Number(x.bales||x.rolls||0),0);
  const totalKg=S.cuts.reduce((sum,x)=>sum+Number(x.total_kg||0),0);
  const cutHa=S.cuts.reduce((sum,x)=>{const lot=S.lots.find(l=>l.id===x.lot_id);return sum+Number(lot?.hectares||lot?.area_ha||0)},0);
  const yieldPerHa=cutHa?rolls/cutHa:0;
  const pendingOrders=S.orders.filter(x=>String(x.status||'').toLowerCase()!=='completada').length;
  const lotsWithGeometry=new Set(S.geometries.map(g=>g.lot_id)).size;
  const irrigationCount=S.irrigations.length;
  const income=S.movements.reduce((sum,x)=>sum+Number(x.income||0),0);
  const expense=S.movements.reduce((sum,x)=>sum+Number(x.cost||0),0);
  const lastActivity=[...S.irrigations.map(x=>x.event_date||x.irrigation_date),...S.cuts.map(x=>x.cut_date),...S.analyses.map(x=>x.flight_date)].filter(Boolean).sort().reverse()[0];
  const cropCards=cropSummary.slice(0,3).map(([crop,ha])=>`<div class="dashboard-crop"><span>${esc(crop)}</span><b>${hectares(ha)}</b></div>`).join('')||'<div class="dashboard-crop"><span>Cultivos</span><b>Sin datos</b></div>';
  return `<div class="hero"><div class="dashboard-hero"><div><p class="eyebrow">CENTRO DE CONTROL ENTERPRISE</p><h2>Buenas tardes, Franco</h2><p>Resumen operativo de ${esc(S.companies.find(c=>c.id===S.companyId)?.name||'la empresa')}.</p></div><div class="status dashboard-weather"><b>🌦 ${weather}</b><small>Pronóstico actualizado automáticamente</small></div></div></div>
  <div class="dashboard-primary metrics">
    <div class="metric"><span>Superficie productiva</span><b>${hectares(totalHa())}</b><small>${activeLots.length} lotes activos</small></div>
    <div class="metric"><span>Producción registrada</span><b>${number(rolls)} rollos</b><small>${totalKg?`${number(totalKg/1000,1)} t acumuladas`:`${S.cuts.length} cortes cargados`}</small></div>
    <div class="metric"><span>NDVI promedio</span><b>${S.analyses.length?number(avgNdvi(),2):'—'}</b><small>${S.analyses.length} análisis procesados</small></div>
    <div class="metric"><span>Alertas activas</span><b>${alerts+pendingOrders}</b><small>${alerts} agronómicas · ${pendingOrders} órdenes</small></div>
  </div>
  <div class="dashboard-strip">${cropCards}<div class="dashboard-crop"><span>Georreferenciados</span><b>${lotsWithGeometry}/${activeLots.length}</b></div></div>
  <div class="grid2 dashboard-main-grid"><div class="panel"><div class="panel-title"><div><p class="eyebrow">SEGUIMIENTO AGRONÓMICO</p><h3>Estado por lote</h3></div><button class="secondary goMap">Abrir mapa</button></div><div class="dashboard-lot-list">${activeLots.slice(0,8).map(l=>{const a=latest(l),v=vigor(a?.ndvi_avg),lastIrr=S.irrigations.find(x=>x.lot_id===l.id),lastCut=S.cuts.find(x=>x.lot_id===l.id),lotRolls=S.cuts.filter(x=>x.lot_id===l.id).reduce((n,x)=>n+Number(x.bales||x.rolls||0),0);return `<article class="dashboard-lot"><div class="dashboard-lot-head"><div><b>${esc(l.name)}</b><small>${esc(l.crop||'Sin cultivo')} · ${hectares(l.hectares||l.area_ha)}</small></div><span class="pill ${v[1]}">${v[0]}</span></div><div class="dashboard-lot-data"><span>NDVI <b>${a?number(a.ndvi_avg,2):'—'}</b></span><span>Último riego <b>${shortDate(lastIrr?.event_date||lastIrr?.irrigation_date||l.last_irrigation)}</b></span><span>Último corte <b>${shortDate(lastCut?.cut_date||l.last_cut)}</b></span><span>Producción <b>${number(lotRolls)} rollos</b></span></div></article>`}).join('')||'<p class="empty">Todavía no hay lotes cargados.</p>'}</div></div>
  <div class="dashboard-side"><div class="panel"><div class="panel-title"><h3>Operación</h3></div><div class="dashboard-ops"><div><span>Riegos registrados</span><b>${number(irrigationCount)}</b></div><div><span>Rendimiento promedio</span><b>${yieldPerHa?`${number(yieldPerHa,1)} rollos/ha`:'Sin datos'}</b></div><div><span>Resultado acumulado</span><b>${money(income-expense)}</b></div><div><span>Última actividad</span><b>${shortDate(lastActivity)}</b></div></div></div><div class="panel"><div class="panel-title"><h3>Acciones rápidas</h3></div><div class="actions dashboard-actions"><button class="primary newAnalysis">Importar vuelo</button><button class="secondary goMap">Dibujar lotes</button><button class="secondary newOrder">Crear orden T100</button><button class="secondary goPortal">Portal cliente</button></div><hr><h3>Alertas operativas</h3>${alerts?`<p class="status">${alerts} lote(s) requieren revisión por vigor.</p>`:'<p class="status">Sin alertas agronómicas críticas.</p>'}${pendingOrders?`<p class="status">${pendingOrders} orden(es) T100 pendientes.</p>`:''}${lotsWithGeometry<activeLots.length?`<p class="status">${activeLots.length-lotsWithGeometry} lote(s) todavía no tienen polígono.</p>`:''}</div></div></div>`
}
function managementPage(){const income=S.movements.filter(x=>String(x.type||x.movement_type||'').toLowerCase().includes('ing')).reduce((a,x)=>a+Number(x.amount||0),0),expense=S.movements.filter(x=>String(x.type||x.movement_type||'').toLowerCase().includes('egr')).reduce((a,x)=>a+Number(x.amount||0),0),rolls=S.cuts.reduce((a,x)=>a+Number(x.bales||x.rolls||0),0),haDrone=S.analyses.reduce((a,x)=>a+Number(x.hectares||0),0);return `<div class="page-head"><div><p class="eyebrow">DIRECCIÓN Y CONTROL</p><h2>Tablero gerencial</h2><p class="muted">Indicadores productivos, operativos y financieros consolidados.</p></div></div><div class="metrics"><div class="metric"><span>Ingresos</span><b>${money(income)}</b><small>movimientos registrados</small></div><div class="metric"><span>Egresos</span><b>${money(expense)}</b><small>costos registrados</small></div><div class="metric"><span>Resultado</span><b>${money(income-expense)}</b><small>margen acumulado</small></div><div class="metric"><span>Rollos producidos</span><b>${rolls}</b><small>${S.cuts.length} cortes</small></div></div><div class="grid2"><div class="panel"><h3>Operación</h3><div class="row"><b>Superficie gestionada</b><span class="pill">${totalHa()} ha</span></div><div class="row"><b>Hectáreas monitoreadas</b><span class="pill">${haDrone.toFixed(1)} ha</span></div><div class="row"><b>Órdenes T100 activas</b><span class="pill">${S.orders.filter(x=>x.status!=='Completada').length}</span></div><div class="row"><b>Clientes registrados</b><span class="pill">${S.clients.length}</span></div><div class="row"><b>Viajes registrados</b><span class="pill">${S.trips.length}</span></div></div><div class="panel"><h3>Prioridades de gestión</h3>${S.lots.filter(l=>Number(latest(l)?.ndvi_avg||1)<.62).slice(0,5).map(l=>`<div class="row"><div><b>${esc(l.name)}</b><small>Revisar vigor, humedad y nutrición.</small></div><span class="pill warn">Atención</span></div>`).join('')||'<div class="empty">No hay prioridades críticas.</div>'}</div></div>`}
function weatherPage(){const w=S.weather;if(!w)return `<div class="panel empty"><h2>Centro meteorológico</h2><p>No fue posible obtener el pronóstico. Verifique la conexión a internet.</p><button class="primary refreshWeather">Reintentar</button></div>`;const c=w.current,d=w.daily;return `<div class="page-head"><div><p class="eyebrow">CLIMA Y OPERACIONES</p><h2>Centro meteorológico</h2><p class="muted">Santiago Temple · pronóstico operativo de 7 días.</p></div><button class="secondary refreshWeather">Actualizar</button></div><div class="hero"><div class="grid2"><div><p class="eyebrow">CONDICIONES ACTUALES</p><h2>${Number(c.temperature_2m).toFixed(1)} °C · ${weatherText(c.weather_code)}</h2><p>Humedad ${c.relative_humidity_2m}% · Viento ${Number(c.wind_speed_10m).toFixed(0)} km/h</p></div><div class="status" style="background:#ffffff18;color:#fff"><b>Ventana operativa</b><p style="margin:8px 0 0">${Number(c.wind_speed_10m)<=18?'Condiciones compatibles con inspección y vuelo, sujeto a ráfagas locales.':'Viento elevado: postergar vuelos y aplicaciones sensibles.'}</p></div></div></div><div class="grid3">${d.time.map((day,i)=>`<article class="panel"><span class="pill">${new Date(day+'T12:00:00').toLocaleDateString('es-AR',{weekday:'short',day:'2-digit',month:'2-digit'})}</span><h3 style="margin-top:14px">${weatherText(d.weather_code[i])}</h3><p><b>${Math.round(d.temperature_2m_max[i])}°</b> / ${Math.round(d.temperature_2m_min[i])}°</p><p>💧 Lluvia ${Number(d.precipitation_sum[i]||0).toFixed(1)} mm</p><p>☔ Prob. ${Number(d.precipitation_probability_max[i]||0).toFixed(0)}%</p><p>ET₀ ${Number(d.et0_fao_evapotranspiration[i]||0).toFixed(1)} mm</p></article>`).join('')}</div>`}
function aiPage(){return `<div class="page-head"><div><p class="eyebrow">ASISTENTE OPERATIVO</p><h2>LM AI</h2><p class="muted">Consultas sobre clima, riego, lotes, NDVI, producción, clientes, transporte y órdenes T100.</p></div></div><div class="grid2"><div class="panel"><h3>Hacer una consulta</h3><label>Pregunta<textarea id="aiQuestion" placeholder="Ejemplo: ¿Qué lotes debería revisar o regar primero?"></textarea></label><div class="actions"><button id="askAi" class="primary">Consultar</button></div><div id="aiResponse" class="status" style="margin-top:16px">Escriba una pregunta para analizar los datos actuales de la empresa.</div></div><div class="panel"><h3>Consultas sugeridas</h3><div class="row"><div><b>Riego</b><small>¿Qué lotes conviene regar primero?</small></div></div><div class="row"><div><b>Clima</b><small>¿Cómo estará el viento y la lluvia?</small></div></div><div class="row"><div><b>Precisión</b><small>¿Qué lotes tienen NDVI bajo?</small></div></div><div class="row"><div><b>Operación</b><small>¿Cuántas órdenes T100 están pendientes?</small></div></div><div class="row"><div><b>Producción</b><small>¿Cuántos rollos de alfalfa hay registrados?</small></div></div></div></div>`}
function portalPage(){const alerts=S.lots.filter(l=>Number(latest(l)?.ndvi_avg||1)<.62);return `<div class="page-head"><div><p class="eyebrow">VISTA DEL PRODUCTOR</p><h2>Portal de clientes</h2><p class="muted">Resumen seguro de la empresa seleccionada.</p></div></div><div class="client-card"><h2>${esc(S.companies.find(c=>c.id===S.companyId)?.name||'Empresa')}</h2><div class="metrics"><div class="metric"><span>Superficie</span><b>${totalHa()} ha</b></div><div class="metric"><span>Vuelos</span><b>${S.analyses.length}</b></div><div class="metric"><span>Alertas</span><b>${alerts.length}</b></div><div class="metric"><span>Órdenes pendientes</span><b>${S.orders.filter(x=>x.status!=='Completada').length}</b></div></div></div><div class="panel" style="margin-top:18px"><h3>Recomendaciones recientes</h3>${S.analyses.slice(0,6).map(a=>`<div class="row"><div><b>${esc(S.lots.find(l=>l.id===a.lot_id)?.name||'Lote')} · ${a.flight_date}</b><small>${esc(a.recommendation||a.observations||'Sin observaciones')}</small></div><span class="pill">NDVI ${Number(a.ndvi_avg||0).toFixed(2)}</span></div>`).join('')||'<div class="empty">Sin informes todavía.</div>'}</div>`}

function irrigationPage(){const eto=4.8,rain=0;const cards=S.lots.map(l=>{const last=S.irrigations.find(x=>x.lot_id===l.id),days=last?Math.max(0,Math.floor((Date.now()-new Date(last.event_date||last.irrigation_date).getTime())/86400000)):7,kc=(l.crop||'').toLowerCase().includes('alfalfa')?1.05:.85,def=Math.max(0,days*eto*kc-rain-Number(last?.millimeters||last?.mm||0)*.15),hrs=def/4.5,prio=def>25?'Urgente':def>15?'Alta':def>7?'Media':'Correcto';return {l,days,def,hrs,prio}});return `<div class="page-head"><div><p class="eyebrow">BALANCE HÍDRICO</p><h2>Riego inteligente</h2><p class="muted">Estimación orientativa con ET₀ 4,8 mm/día. Confirmar con humedad de suelo y recorrido.</p></div></div><div class="grid3">${cards.map(x=>`<article class="analysis-card"><div class="panel-title"><b>${esc(x.l.name)}</b><span class="pill ${x.prio==='Urgente'?'bad':x.prio==='Alta'||x.prio==='Media'?'warn':''}">${x.prio}</span></div><b class="big">${x.def.toFixed(1)} mm</b><p>${x.days} días desde el último riego registrado</p><p><b>${x.hrs.toFixed(1)} h</b> sugeridas a 4,5 mm/h</p><small class="muted">Cultivo: ${esc(x.l.crop||'—')} · ${Number(x.l.hectares||0)} ha</small></article>`).join('')}</div>`}
function clientsPage(){return `<div class="page-head"><div><p class="eyebrow">CRM</p><h2>Clientes</h2></div></div><div class="panel">${S.clients.map(c=>`<div class="row"><div><b>${esc(c.name||c.client_name||'Cliente')}</b><small>${esc(c.phone||c.whatsapp||'')} ${esc(c.location||'')}</small></div><span class="pill">${esc(c.status||'Activo')}</span></div>`).join('')||'<div class="empty">Todavía no hay clientes cargados.</div>'}</div>`}
function transportPage(){const km=S.trips.reduce((s,x)=>s+Number(x.kilometers||x.km||0),0),income=S.trips.reduce((s,x)=>s+Number(x.income||x.amount||0),0),cost=S.trips.reduce((s,x)=>s+Number(x.cost||x.total_cost||0),0);return `<div class="page-head"><div><p class="eyebrow">LOGÍSTICA</p><h2>Transporte</h2></div></div><div class="metrics"><div class="metric"><span>Viajes</span><b>${S.trips.length}</b></div><div class="metric"><span>Kilómetros</span><b>${km.toFixed(0)}</b></div><div class="metric"><span>Ingresos</span><b>$ ${income.toLocaleString('es-AR')}</b></div><div class="metric"><span>Margen</span><b>$ ${(income-cost).toLocaleString('es-AR')}</b></div></div><div class="panel"><h3>Últimos viajes</h3>${S.trips.slice(0,10).map(t=>`<div class="row"><div><b>${esc(t.client_name||t.destination||'Viaje')}</b><small>${esc(t.origin||'')} → ${esc(t.destination||'')} · ${Number(t.kilometers||t.km||0)} km</small></div><span class="pill">${esc(t.status||'Registrado')}</span></div>`).join('')||'<div class="empty">Sin viajes registrados.</div>'}</div>`}
function adminPage(){
  const inc=S.movements.filter(x=>(x.type||x.movement_type||'').toLowerCase().includes('ing')).reduce((s,x)=>s+Number(x.amount||0),0),out=S.movements.filter(x=>!(x.type||x.movement_type||'').toLowerCase().includes('ing')).reduce((s,x)=>s+Number(x.amount||0),0);
  const canManage=['Administrador','Superadministrador'].includes(currentRole());
  const memberRows=S.members.map(m=>`<tr><td><b>${esc(m.full_name||m.email||'Usuario')}</b><small>${esc(m.email||'')}</small></td><td>${canManage&&m.user_id!==S.session?.user?.id?`<select class="memberRole" data-id="${m.id}">${['Administrador','Encargado','Operario','Asesor','Cliente'].map(r=>`<option ${m.role===r?'selected':''}>${r}</option>`).join('')}</select>`:`<span class="pill">${esc(m.role)}</span>`}</td><td>${shortDate(m.created_at)}</td><td>${canManage&&m.user_id!==S.session?.user?.id?`<button class="secondary removeMember" data-id="${m.id}">Quitar</button>`:'—'}</td></tr>`).join('');
  const inviteRows=S.invitations.map(i=>`<tr><td><b>${esc(i.full_name||i.email)}</b><small>${esc(i.email)}</small></td><td><span class="pill">${esc(i.role)}</span></td><td><span class="pill ${i.status==='Pendiente'?'warn':''}">${esc(i.status)}</span></td><td>${shortDate(i.expires_at)}</td><td>${canManage&&i.status==='Pendiente'?`<button class="secondary revokeInvite" data-id="${i.id}">Revocar</button>`:'—'}</td></tr>`).join('');
  return `<div class="page-head"><div><p class="eyebrow">GESTIÓN Y SEGURIDAD</p><h2>Administración</h2><p class="muted">Finanzas, usuarios, roles e invitaciones de ${esc(S.companies.find(c=>c.id===S.companyId)?.name||'la empresa')}.</p></div>${canManage?'<button class="primary newInvite">+ Invitar usuario</button>':''}</div><div class="metrics"><div class="metric"><span>Ingresos</span><b>${money(inc)}</b></div><div class="metric"><span>Egresos</span><b>${money(out)}</b></div><div class="metric"><span>Resultado</span><b>${money(inc-out)}</b></div><div class="metric"><span>Usuarios activos</span><b>${S.members.length}</b><small>${S.invitations.filter(i=>i.status==='Pendiente').length} invitaciones pendientes</small></div></div><div class="grid2" style="margin-top:18px"><div class="panel"><p class="eyebrow">MI ACCESO</p><h3>${esc(S.membership?.full_name||S.session?.user?.email||'Usuario')}</h3><div class="row"><span>${esc(S.session?.user?.email||'')}</span><span class="pill">${esc(currentRole())}</span></div><p class="muted">Los permisos también están protegidos por RLS dentro de Supabase.</p></div><div class="panel"><p class="eyebrow">RESUMEN DE PERMISOS</p><h3>${canManage?'Administración habilitada':'Acceso limitado por rol'}</h3><p class="muted">${canManage?'Podés invitar usuarios, cambiar roles y revocar accesos.':'Solo un Administrador puede modificar usuarios y permisos.'}</p></div></div><div class="panel" style="margin-top:18px"><div class="panel-title"><h3>Equipo de la empresa</h3><span class="pill">${S.members.length} miembros</span></div><div style="overflow:auto"><table class="table"><thead><tr><th>Usuario</th><th>Rol</th><th>Alta</th><th></th></tr></thead><tbody>${memberRows||'<tr><td colspan="4">No hay miembros visibles.</td></tr>'}</tbody></table></div></div><div class="panel" style="margin-top:18px"><div class="panel-title"><h3>Invitaciones</h3><span class="pill">${S.invitations.length}</span></div><div style="overflow:auto"><table class="table"><thead><tr><th>Persona</th><th>Rol</th><th>Estado</th><th>Vence</th><th></th></tr></thead><tbody>${inviteRows||'<tr><td colspan="5" class="muted">No hay invitaciones registradas.</td></tr>'}</tbody></table></div><p class="muted">La persona debe crear o ingresar con esta misma dirección de correo. Al iniciar sesión, la invitación se acepta automáticamente.</p></div>`}
function invitationModal(){modal(`<p class="eyebrow">SEGURIDAD SAAS</p><h2>Invitar usuario</h2><form id="inviteForm"><div class="form-grid"><label>Nombre completo<input name="full_name" required></label><label>Correo electrónico<input name="email" type="email" required></label><label>Rol<select name="role"><option>Encargado</option><option>Operario</option><option>Asesor</option><option>Cliente</option><option>Administrador</option></select></label><label>Vigencia<select name="days"><option value="7">7 días</option><option value="14" selected>14 días</option><option value="30">30 días</option></select></label></div><div class="status">La invitación queda registrada. Compartí la URL pública de LA MAGDALENA OS con la persona; debe registrarse usando exactamente este correo.</div><button class="primary">Crear invitación</button><p id="inviteMsg" class="error hidden"></p></form>`);$('#inviteForm').onsubmit=saveInvitation}
async function saveInvitation(e){e.preventDefault();const f=new FormData(e.target),days=Number(f.get('days')||14),row={company_id:S.companyId,email:String(f.get('email')).trim().toLowerCase(),full_name:f.get('full_name'),role:f.get('role'),invited_by:S.session.user.id,expires_at:new Date(Date.now()+days*86400000).toISOString()};const {error}=await sb.from('company_invitations').insert(row);if(error){$('#inviteMsg').textContent=error.message;$('#inviteMsg').classList.remove('hidden');return}$('#modalRoot').innerHTML='';await loadData();render()}
async function updateMemberRole(id,role){const {error}=await sb.from('company_members').update({role}).eq('id',id);if(error)return alert(error.message);await loadData();render()}
async function removeMember(id){if(!confirm('¿Quitar el acceso de este usuario a la empresa?'))return;const {error}=await sb.from('company_members').delete().eq('id',id);if(error)return alert(error.message);await loadData();render()}
async function revokeInvitation(id){const {error}=await sb.from('company_invitations').update({status:'Revocada'}).eq('id',id);if(error)return alert(error.message);await loadData();render()}
function aiAnswer(q){const t=(q||'').toLowerCase(),w=S.weather?.current,d=S.weather?.daily;const low=S.lots.filter(l=>Number(latest(l)?.ndvi_avg||1)<.62),pending=S.orders.filter(x=>x.status!=='Completada'),rain=d?d.precipitation_sum.reduce((a,x)=>a+Number(x||0),0):0;if(!t)return 'Escriba una pregunta sobre riego, clima, lotes, producción, drones, transporte o finanzas.';if(t.includes('regar')||t.includes('riego'))return low.length?`Priorice ${low.slice(0,4).map(x=>x.name).join(', ')}. Hay ${rain.toFixed(1)} mm previstos en 7 días. Confirme la decisión con humedad de suelo y estado del cultivo.`:`No hay lotes con alerta NDVI. Hay ${rain.toFixed(1)} mm previstos en 7 días; revise el balance hídrico antes de regar.`;if(t.includes('clima')||t.includes('viento')||t.includes('lluvia'))return w?`Ahora: ${Number(w.temperature_2m).toFixed(1)} °C, ${weatherText(w.weather_code)}, viento ${Number(w.wind_speed_10m).toFixed(0)} km/h y humedad ${w.relative_humidity_2m}%. Lluvia acumulada prevista: ${rain.toFixed(1)} mm.`:'No pude obtener el clima en este momento.';if(t.includes('t100')||t.includes('orden'))return `Hay ${pending.length} órdenes T100 pendientes y ${S.orders.length} órdenes totales.`;if(t.includes('ndvi')||t.includes('lote'))return `NDVI promedio ${avgNdvi().toFixed(2)}. ${low.length?`Revisar: ${low.map(x=>x.name).join(', ')}.`:'No hay alertas de vigor.'}`;if(t.includes('rollo')||t.includes('alfalfa'))return `Hay ${S.cuts.length} cortes registrados y ${S.cuts.reduce((a,x)=>a+Number(x.bales||x.rolls||0),0)} rollos acumulados.`;if(t.includes('cliente'))return `La empresa tiene ${S.clients.length} clientes registrados.`;if(t.includes('viaje')||t.includes('scania')||t.includes('transporte')){const ingreso=S.trips.reduce((a,x)=>a+Number(x.income||0),0),costo=S.trips.reduce((a,x)=>a+Number(x.cost||0),0),km=S.trips.reduce((a,x)=>a+Number(x.kilometers||0),0);return `Hay ${S.trips.length} viajes registrados, ${number(km)} km recorridos y un margen acumulado de ${money(ingreso-costo)}.`;}return `Resumen: ${S.lots.length} lotes, ${totalHa()} ha, NDVI ${avgNdvi().toFixed(2)}, ${low.length} alertas y ${pending.length} órdenes T100 pendientes.`}
function saasPage(){const active=S.companies.filter(c=>(c.status||'active')==='active').length,mrr=S.companies.reduce((sum,c)=>sum+Number(c.monthly_price||0),0);return `<div class="page-head"><div><p class="eyebrow">ADMINISTRACIÓN DE LA PLATAFORMA</p><h2>Centro SaaS</h2><p class="muted">Empresas, planes, módulos y estado comercial de cada cliente.</p></div><div class="actions"><button class="primary newCompany">+ Nueva empresa</button></div></div><div class="metrics"><div class="metric"><span>Empresas</span><b>${S.companies.length}</b><small>${active} activas</small></div><div class="metric"><span>MRR estimado</span><b>$ ${mrr.toLocaleString('es-AR')}</b><small>ingreso mensual</small></div><div class="metric"><span>Planes premium</span><b>${S.companies.filter(c=>['premium','enterprise'].includes(c.plan)).length}</b><small>cuentas avanzadas</small></div><div class="metric"><span>Implementación</span><b>${S.companies.filter(c=>(c.onboarding_status||'pending')!=='complete').length}</b><small>clientes pendientes</small></div></div><div class="panel"><div class="panel-title"><h3>Cartera de clientes</h3><span class="pill">Superadministrador</span></div><div style="overflow:auto"><table class="table"><thead><tr><th>Empresa</th><th>Ubicación</th><th>Plan</th><th>Estado</th><th>Precio mensual</th><th>Módulos</th><th></th></tr></thead><tbody>${S.companies.map(c=>{const mods=S.modules.filter(m=>m.company_id===c.id&&m.enabled).length;return `<tr><td><b>${esc(c.name)}</b><small>${esc(c.legal_name||'')}</small></td><td>${esc(c.location||'-')}</td><td>${planLabel(c.plan)}</td><td><span class="pill ${(c.status==='active'||!c.status)?'':'warn'}">${esc(c.status||'active')}</span></td><td>$ ${Number(c.monthly_price||0).toLocaleString('es-AR')}</td><td>${mods}</td><td><button class="secondary editCompany" data-id="${c.id}">Administrar</button></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">No hay empresas.</td></tr>'}</tbody></table></div></div><div class="grid3" style="margin-top:18px"><div class="panel"><h3>Planes sugeridos</h3><div class="row"><div><b>Básico</b><small>Lotes, agenda y reportes</small></div></div><div class="row"><div><b>Profesional</b><small>Riego, maquinaria y costos</small></div></div><div class="row"><div><b>Premium</b><small>Precisión, drones y LM AI</small></div></div></div><div class="panel"><h3>Modelo comercial</h3><p class="muted">Suscripción mensual más servicios administrados de drones, mapas e informes agronómicos.</p><div class="status">Cada empresa mantiene sus datos separados mediante políticas RLS.</div></div><div class="panel"><h3>Publicación web</h3><p class="muted">El paquete incluye una guía para desplegar la aplicación y conectar un dominio propio.</p><div class="status">La clave administrativa nunca debe colocarse en el navegador.</div></div></div>`}
function companyModal(company=null){const enabled=new Set(S.modules.filter(m=>m.company_id===company?.id&&m.enabled).map(m=>m.module_key));const all=['dashboard','production','precision','irrigation','drones','lots','clients','sales','purchases','finance','transport','resources','campaigns','admin','ai','portal'];modal(`<p class="eyebrow">V10 ENTERPRISE</p><h2>${company?'Administrar empresa':'Nueva empresa'}</h2><form id="companyForm"><input type="hidden" name="id" value="${company?.id||''}"><div class="form-grid"><label>Nombre comercial<input name="name" value="${esc(company?.name||'')}" required></label><label>Razón social<input name="legal_name" value="${esc(company?.legal_name||'')}"></label><label>Ubicación<input name="location" value="${esc(company?.location||'')}"></label><label>Plan<select name="plan"><option value="basic" ${company?.plan==='basic'?'selected':''}>Básico</option><option value="professional" ${company?.plan==='professional'?'selected':''}>Profesional</option><option value="premium" ${company?.plan==='premium'?'selected':''}>Premium</option><option value="enterprise" ${company?.plan==='enterprise'?'selected':''}>Enterprise</option></select></label><label>Estado<select name="status"><option value="active" ${(company?.status||'active')==='active'?'selected':''}>Activa</option><option value="trial" ${company?.status==='trial'?'selected':''}>Prueba</option><option value="suspended" ${company?.status==='suspended'?'selected':''}>Suspendida</option></select></label><label>Precio mensual<input name="monthly_price" type="number" step="1" value="${Number(company?.monthly_price||0)}"></label><label>Implementación<select name="onboarding_status"><option value="pending" ${(company?.onboarding_status||'pending')==='pending'?'selected':''}>Pendiente</option><option value="in_progress" ${company?.onboarding_status==='in_progress'?'selected':''}>En curso</option><option value="complete" ${company?.onboarding_status==='complete'?'selected':''}>Completa</option></select></label><label>Vencimiento<input name="subscription_expires_at" type="date" value="${company?.subscription_expires_at?.slice?.(0,10)||''}"></label><div class="wide"><b>Módulos habilitados</b><div class="grid3" style="margin-top:10px">${all.map(k=>`<label style="display:flex;grid-template-columns:auto 1fr;align-items:center"><input style="width:auto" type="checkbox" name="module" value="${k}" ${enabled.has(k)||(!company&&['dashboard','lots','clients'].includes(k))?'checked':''}> ${k}</label>`).join('')}</div></div></div><button class="primary">Guardar empresa</button><p id="cm" class="error hidden"></p></form>`);$('#companyForm').onsubmit=saveCompany}
async function saveCompany(e){e.preventDefault();const f=new FormData(e.target),id=f.get('id'),row={name:f.get('name'),legal_name:f.get('legal_name')||null,location:f.get('location')||null,plan:f.get('plan'),status:f.get('status'),monthly_price:Number(f.get('monthly_price')||0),onboarding_status:f.get('onboarding_status'),subscription_expires_at:f.get('subscription_expires_at')||null};try{let companyId=id;if(id){const {error}=await sb.from('companies').update(row).eq('id',id);if(error)throw error}else{row.created_by=S.session.user.id;const {data,error}=await sb.from('companies').insert(row).select().single();if(error)throw error;companyId=data.id}const mods=[...f.getAll('module')];await sb.from('company_modules').delete().eq('company_id',companyId);if(mods.length){const {error}=await sb.from('company_modules').insert(mods.map(module_key=>({company_id:companyId,module_key,enabled:true})));if(error)throw error}$('#modalRoot').innerHTML='';await loadCompanies();await loadData();S.page='saas';render()}catch(err){$('#cm').textContent=err.message;$('#cm').classList.remove('hidden')}}

function bind(){lotsModule.bind();document.querySelectorAll('.newInvite').forEach(b=>b.onclick=invitationModal);document.querySelectorAll('.memberRole').forEach(x=>x.onchange=()=>updateMemberRole(x.dataset.id,x.value));document.querySelectorAll('.removeMember').forEach(b=>b.onclick=()=>removeMember(b.dataset.id));document.querySelectorAll('.revokeInvite').forEach(b=>b.onclick=()=>revokeInvitation(b.dataset.id));document.querySelectorAll('.refreshWeather').forEach(b=>b.onclick=async()=>{await loadWeather();render()});document.querySelectorAll('.newCompany').forEach(b=>b.onclick=()=>companyModal());document.querySelectorAll('.editCompany').forEach(b=>b.onclick=()=>companyModal(S.companies.find(c=>c.id===b.dataset.id)));productionModule.bind();salesModule.bind();purchasesModule.bind();financeModule.bind();dataSafetyModule.bind();transportModule.bind();resourcesModule.bind();campaignsModule.bind();operationsModule.bind();const content=$('#content');content.onclick=e=>{const newLot=e.target.closest('.newLot');if(newLot){lotsModule.openEditor();return}const editLot=e.target.closest('.editLot');if(editLot){const lot=S.lots.find(item=>item.id===editLot.dataset.id);if(lot)lotsModule.openEditor(lot);return}const lotDetail=e.target.closest('.lotDetail');if(lotDetail){const lot=S.lots.find(item=>item.id===lotDetail.dataset.id);if(lot)lotsModule.openDetails(lot)}};const ask=$('#askAi');if(ask)ask.onclick=()=>{$('#aiResponse').textContent=aiAnswer($('#aiQuestion').value)};document.querySelectorAll('.newAnalysis').forEach(b=>b.onclick=analysisModal);document.querySelectorAll('.newOrder').forEach(b=>b.onclick=()=>orderModal());document.querySelectorAll('.goMap').forEach(b=>b.onclick=()=>{S.page='map';render()});document.querySelectorAll('.goProduction').forEach(b=>b.onclick=()=>{S.page='production';render()});document.querySelectorAll('.goPortal').forEach(b=>b.onclick=()=>{S.page='portal';render()});document.querySelectorAll('.makeOrder').forEach(b=>b.onclick=()=>orderFromAnalysis(b.dataset.id));document.querySelectorAll('.openFile').forEach(b=>b.onclick=()=>openStoredFile(b.dataset.path))}
function modal(html){$('#modalRoot').innerHTML=`<div class="modal-wrap"><div class="modal"><button class="close">×</button>${html}</div></div>`;$('.close').onclick=()=>$('#modalRoot').innerHTML=''}

function analysisModal(){modal(`<p class="eyebrow">ANÁLISIS MULTIESPECTRAL</p><h2>Importar vuelo procesado</h2><form id="analysisForm"><div class="form-grid"><label>Fecha<input name="flight_date" type="date" required></label><label>Lote<select name="lot_id" required><option value="">Seleccionar</option>${S.lots.map(l=>`<option value="${l.id}">${esc(l.name)}</option>`).join('')}</select></label><label>Superficie (ha)<input name="hectares" type="number" step=".1" required></label><label>CSV de zonas<input name="csv" type="file" accept=".csv,text/csv" required></label><label>Mapa procesado (opcional)<input name="map" type="file" accept="image/*,.pdf,.tif,.tiff"></label><label class="wide">Observaciones<textarea name="observations"></textarea></label></div><p class="status">CSV requerido: zone,ndvi,ndre,area_ha. Se calcularán promedios y porcentaje de bajo vigor automáticamente.</p><button class="primary">Procesar y guardar</button><p id="am" class="error hidden"></p></form>`);$('#analysisForm').onsubmit=saveAnalysis}
function parseCSV(text){const lines=text.trim().split(/\r?\n/).filter(Boolean),headers=lines.shift().split(',').map(x=>x.trim().toLowerCase());const req=['zone','ndvi','ndre','area_ha'];if(req.some(x=>!headers.includes(x)))throw new Error('El CSV debe contener: zone, ndvi, ndre, area_ha');return lines.map(line=>{const vals=line.split(',');const o={};headers.forEach((h,i)=>o[h]=vals[i]?.trim());return{zone:o.zone,ndvi:Number(o.ndvi),ndre:Number(o.ndre),area_ha:Number(o.area_ha)}}).filter(x=>Number.isFinite(x.ndvi)&&Number.isFinite(x.ndre)&&Number.isFinite(x.area_ha))}
async function uploadFile(file,folder){if(!file)return null;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${S.companyId}/${folder}/${Date.now()}_${safe}`;const {error}=await sb.storage.from('precision-files').upload(path,file,{upsert:false});if(error)throw error;return path}
async function saveAnalysis(e){e.preventDefault();const f=new FormData(e.target),msg=$('#am');try{const csv=f.get('csv'),zones=parseCSV(await csv.text());if(!zones.length)throw new Error('El CSV no tiene filas válidas.');const weighted=(key)=>zones.reduce((s,z)=>s+z[key]*z.area_ha,0)/zones.reduce((s,z)=>s+z.area_ha,0);const vals=k=>zones.map(z=>z[k]);const lowArea=zones.filter(z=>z.ndvi<.55).reduce((s,z)=>s+z.area_ha,0),total=zones.reduce((s,z)=>s+z.area_ha,0),ndvi=weighted('ndvi'),ndre=weighted('ndre');const csvPath=await uploadFile(csv,'csv'),mapPath=await uploadFile(f.get('map')?.size?f.get('map'):null,'maps');const lowPct=total?lowArea/total*100:0;const recommendation=ndvi<.45?'Prioridad alta: inspeccionar estrés hídrico, fallas de implantación o nutrición.':ndvi<.62?'Vigor medio: recorrer sectores de menor índice y verificar humedad/nutrición.':'Vigor general adecuado; mantener seguimiento y comparar con el próximo vuelo.';const row={company_id:S.companyId,lot_id:f.get('lot_id'),flight_date:f.get('flight_date'),hectares:Number(f.get('hectares')),ndvi_avg:ndvi,ndvi_min:Math.min(...vals('ndvi')),ndvi_max:Math.max(...vals('ndvi')),ndre_avg:ndre,ndre_min:Math.min(...vals('ndre')),ndre_max:Math.max(...vals('ndre')),low_vigor_pct:lowPct,zones_count:zones.length,source_file_path:csvPath,map_file_path:mapPath,zones_json:zones,observations:f.get('observations')||null,recommendation,created_by:S.session.user.id};const {error}=await sb.from('precision_analyses').insert(row);if(error)throw error;$('#modalRoot').innerHTML='';await loadData();render()}catch(err){msg.textContent=err.message;msg.classList.remove('hidden')}}
function orderFromAnalysis(id){const a=S.analyses.find(x=>x.id===id),lot=S.lots.find(x=>x.id===a?.lot_id);orderModal({lot_id:lot?.id,hectares:Math.max(.1,Number(a?.hectares||0)*Number(a?.low_vigor_pct||0)/100),notes:`Generada desde análisis ${a?.flight_date}. Bajo vigor: ${Number(a?.low_vigor_pct||0).toFixed(1)}%. ${a?.recommendation||''}`})}
function orderModal(seed={}){modal(`<p class="eyebrow">DJI AGRAS T100</p><h2>Nueva orden</h2><form id="orderForm"><div class="form-grid"><label>Fecha<input name="order_date" type="date" required></label><label>Lote<select name="lot_id" required><option value="">Seleccionar</option>${S.lots.map(l=>`<option value="${l.id}" ${seed.lot_id===l.id?'selected':''}>${esc(l.name)}</option>`).join('')}</select></label><label>Trabajo<input name="application_type" value="Aplicación localizada" required></label><label>Superficie (ha)<input name="hectares" type="number" step=".1" value="${Number(seed.hectares||0).toFixed(1)}" required></label><label>Producto<input name="product" required></label><label>Dosis<input name="dose" type="number" step=".01" required></label><label>Unidad<select name="dose_unit"><option>L/ha</option><option>kg/ha</option></select></label><label>Estado<select name="status"><option>Planificada</option><option>En curso</option><option>Completada</option></select></label><label class="wide">Notas<textarea name="notes">${esc(seed.notes||'')}</textarea></label></div><button class="primary">Guardar orden</button><p id="om" class="error hidden"></p></form>`);$('#orderForm').onsubmit=saveOrder}
async function saveOrder(e){e.preventDefault();const f=new FormData(e.target),lot=S.lots.find(x=>x.id===f.get('lot_id')),ha=Number(f.get('hectares')),dose=Number(f.get('dose')),row={company_id:S.companyId,lot_id:lot.id,lot_name:lot.name,order_date:f.get('order_date'),application_type:f.get('application_type'),hectares:ha,product:f.get('product'),dose,dose_unit:f.get('dose_unit'),estimated_product:ha*dose,estimated_batteries:Math.ceil(ha/18),estimated_minutes:Math.round(ha*4.5),status:f.get('status'),notes:f.get('notes')||null};const {error}=await sb.from('precision_orders').insert(row);if(error){$('#om').textContent=error.message;$('#om').classList.remove('hidden');return}$('#modalRoot').innerHTML='';await loadData();render()}
async function openStoredFile(path){if(!path)return alert('Este análisis no tiene mapa cargado.');const {data,error}=await sb.storage.from('precision-files').createSignedUrl(path,300);if(error)return alert(error.message);window.open(data.signedUrl,'_blank')}
const productionModule=createProductionModule({state:S,supabase:sb,select:$,escapeHtml:esc,openModal:modal,openOrder:orderModal,loadData,render});
const salesModule=createSalesModule({state:S,supabase:sb,escapeHtml:esc,openModal:modal,loadData,render});
const purchasesModule=createPurchasesModule({state:S,supabase:sb,escapeHtml:esc,openModal:modal,loadData,render});
const dataSafetyModule=createDataSafetyModule({state:S,escapeHtml:esc,render});
const financeModule=createFinanceModule({state:S,supabase:sb,escapeHtml:esc,openModal:modal,loadData,render});
const transportModule=createTransportModule({state:S,supabase:sb,escapeHtml:esc,openModal:modal,loadData,render});
const resourcesModule=createResourcesModule({state:S,supabase:sb,escapeHtml:esc,openModal:modal,loadData,render});
const campaignsModule=createCampaignsModule({state:S,supabase:sb,escapeHtml:esc,openModal:modal,loadData,render});
const operationsModule=createOperationsModule({state:S,escapeHtml:esc,render,setPage:(page)=>{S.page=page;document.querySelectorAll('#nav button[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));render();}});
const lotsModule=createLotsModule({state:S,supabase:sb,select:$,escapeHtml:esc,totalHa,latest,vigor,openModal:modal,openOrder:orderModal,loadData,render});
const gisModule=createGisModule({state:S,supabase:sb,select:$,escapeHtml:esc,number,hectares,shortDate,latest,loadData,render,orderModal,openLotDetails:lot=>lotsModule.openDetails(lot)});

init().catch(e=>{console.error(e);const m=$('#loginMsg');m.textContent='Error al iniciar: '+e.message;m.classList.remove('hidden')})
