export function createGisModule({state, supabase, select, escapeHtml, number, hectares, shortDate, latest, loadData, render, orderModal, openLotDetails}) {
  const S=state, sb=supabase, $=select, esc=escapeHtml;
function mapLotCard(lot){
  if(!lot)return '<p class="muted">Seleccione un lote o haga clic sobre un polígono para abrir su ficha operativa.</p>';
  const a=latest(lot),ir=S.irrigations.find(x=>x.lot_id===lot.id),cut=S.cuts.find(x=>x.lot_id===lot.id),orders=S.orders.filter(x=>x.lot_id===lot.id),rolls=S.cuts.filter(x=>x.lot_id===lot.id).reduce((n,x)=>n+Number(x.bales||x.rolls||0),0),geom=S.geometries.find(x=>x.lot_id===lot.id);
  return `<div class="gis-card-head"><div><span class="pill">${esc(lot.status||'Activo')}</span><h3>${esc(lot.name)}</h3><p>${esc(lot.crop||'Sin cultivo')} · ${hectares(lot.hectares||lot.area_ha)}</p></div><span class="gis-geo-state ${geom?'ok':'warn'}">${geom?'Georreferenciado':'Sin polígono'}</span></div>
  <div class="gis-card-grid"><div><span>NDVI</span><b>${a?.ndvi_avg!=null?number(a.ndvi_avg,2):'Sin datos'}</b></div><div><span>Último riego</span><b>${shortDate(ir?.event_date||ir?.irrigation_date)}</b></div><div><span>Último corte</span><b>${shortDate(cut?.cut_date)}</b></div><div><span>Producción</span><b>${number(rolls)} rollos</b></div><div><span>Órdenes T100</span><b>${orders.length}</b></div><div><span>Campaña</span><b>${esc(lot.campaign||lot.season||'Sin informar')}</b></div></div>
  <div class="gis-card-actions"><button class="secondary gis-open-lot" data-id="${lot.id}">Ver ficha</button><button class="secondary gis-new-irrigation" data-id="${lot.id}">Registrar riego</button><button class="primary gis-new-order" data-id="${lot.id}">Crear orden T100</button></div>`
}
function mapPage(){const selected=S.lots.find(l=>l.id===S.selectedLotId);return `<div class="page-head gis-page-head"><div><p class="eyebrow">GEMELO DIGITAL KML · 26.1.1</p><h2>Centro operativo georreferenciado</h2><p class="muted">Mapa real de La Magdalena: 13 válvulas vinculadas a producción, riego, drones y agricultura de precisión.</p></div><div class="actions"><button class="secondary" id="fitAllBtn">Ver establecimiento</button><button class="primary" id="saveGeometry">Guardar geometría</button></div></div><div class="gis-layout"><aside class="panel gis-sidebar"><h3>Capas y herramientas</h3><label>Lote de trabajo<select id="mapLotSelect"><option value="">Seleccionar lote</option>${S.lots.map(l=>`<option value="${l.id}" ${S.selectedLotId===l.id?'selected':''}>${esc(l.name)}</option>`).join('')}</select></label><div class="gis-layer-list"><label><input type="checkbox" id="layerLots" checked> Lotes guardados</label><label><input type="checkbox" id="layerReference" checked> Mapa real / válvulas</label><label><input type="checkbox" id="layerLabels" checked> Etiquetas</label></div><div class="gis-section"><b>Mapa base</b><div class="actions"><button class="secondary" id="satelliteBtn">Satelital</button><button class="secondary" id="streetBtn">Calles</button></div></div><div class="gis-section"><b>Importar archivo</b><input id="gisFile" type="file" accept=".geojson,.json,.kml,application/geo+json,application/vnd.google-earth.kml+xml"><small class="muted">GeoJSON o KML. El polígono importado queda listo para asociar al lote elegido.</small></div><div class="gis-section"><b>Geometría activa</b><div id="geometryStats" class="gis-stats"><span>Superficie</span><strong>Sin geometría</strong><span>Perímetro</span><strong>—</strong></div><button class="secondary" id="clearDrawingBtn">Limpiar dibujo</button></div><div id="gisLotCard" class="gis-lot-card">${mapLotCard(selected)}</div></aside><section class="gis-map-panel"><div class="gis-toolbar"><span class="status">Centro: Santiago Temple · Coordenadas WGS84</span><span id="gisMessage" class="muted">Haga clic sobre un lote para abrir su ficha operativa.</span></div><div id="map" class="map gis-map"></div></section></div>`}

async function initMap(){
  if(S.map){S.map.remove();S.map=null}
  const center=[-31.332065,-63.311986];
  S.map=L.map('map',{zoomControl:true}).setView(center,15);
  const street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap'});
  const satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:20,attribution:'Esri World Imagery'}).addTo(S.map);
  const savedGroup=L.featureGroup().addTo(S.map),referenceGroup=L.featureGroup().addTo(S.map),labelGroup=L.layerGroup().addTo(S.map);
  S.drawn=new L.FeatureGroup().addTo(S.map);
  const styleForLot=lotId=>{const lot=S.lots.find(x=>x.id===lotId),a=latest(lot||{}),n=Number(a?.ndvi_avg||0),crop=String(lot?.crop||'').toLowerCase();const fill=crop.includes('trigo')?'#c79a2b':crop.includes('alfalfa')?'#238b57':'#4f8ea8';const edge=n&&n<.45?'#b93636':n&&n<.62?'#bd7a16':'#134e3a';return{color:edge,weight:3,fillColor:fill,fillOpacity:.42}};
  const addStats=layer=>{try{const gj=layer.toGeoJSON(),area=turf.area(gj)/10000,len=turf.length(turf.polygonToLine(gj),{units:'kilometers'});$('#geometryStats').innerHTML=`<span>Superficie calculada</span><strong>${number(area,2)} ha</strong><span>Perímetro</span><strong>${number(len,2)} km</strong>`;$('#gisMessage').textContent='Geometría activa lista para guardar.'}catch{$('#geometryStats').innerHTML='<span>Superficie</span><strong>Geometría cargada</strong><span>Perímetro</span><strong>—</strong>'}};
  const bindCardActions=()=>{
    document.querySelectorAll('.gis-open-lot').forEach(b=>b.onclick=()=>{const lot=S.lots.find(x=>x.id===b.dataset.id);if(!lot)return;S.selectedLotId=lot.id;openLotDetails(lot)});
    document.querySelectorAll('.gis-new-order').forEach(b=>b.onclick=()=>orderModal({lot_id:b.dataset.id}));
    document.querySelectorAll('.gis-new-irrigation').forEach(b=>b.onclick=()=>{S.page='irrigation';S.selectedLotId=b.dataset.id;document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page==='irrigation'));render()});
  };
  const selectLot=lotId=>{const lot=S.lots.find(x=>x.id===lotId);if(!lot)return;S.selectedLotId=lotId;if($('#mapLotSelect'))$('#mapLotSelect').value=lotId;$('#gisLotCard').innerHTML=mapLotCard(lot);$('#gisMessage').textContent=`${lot.name} seleccionado · consulte la ficha o genere una tarea.`;bindCardActions()};
  S.geometries.forEach(g=>{try{const l=S.lots.find(x=>x.id===g.lot_id),a=latest(l||{}),layer=L.geoJSON(g.geojson,{style:()=>styleForLot(g.lot_id),onEachFeature:(f,ly)=>{ly.options.lotId=g.lot_id;ly.bindTooltip(`${esc(l?.name||'Lote')} · ${esc(l?.crop||'Sin cultivo')}`,{sticky:true})}});layer.eachLayer(x=>x.options.lotId=g.lot_id);layer.addTo(savedGroup);if(layer.getBounds?.().isValid()){const c=layer.getBounds().getCenter();L.marker(c,{icon:L.divIcon({className:'gis-label',html:`<span>${esc(l?.name||'Lote')}</span>`})}).addTo(labelGroup)}}catch(e){console.warn(e)}});
  try{const response=await fetch('data/mapa-la-magdalena.geojson?version=26.1.1');if(response.ok){const data=await response.json();L.geoJSON(data,{style:f=>{const crop=String(f.properties?.crop||'').toLowerCase();return{color:crop.includes('trigo')?'#8a6514':'#126047',weight:2,dashArray:S.geometries.length?'6 4':null,fillColor:crop.includes('trigo')?'#c79a2b':'#238b57',fillOpacity:S.geometries.length?.14:.42}},onEachFeature:(f,l)=>{const p=f.properties||{};l.bindTooltip(`<b>${esc(p.name||'Sector')}</b><br>${esc(p.crop||'Sin cultivo')} · ${number(p.operational_area_ha||p.area_ha,2)} ha`,{sticky:true});l.on('click',()=>{const lot=S.lots.find(x=>String(x.name||'').toLowerCase()===String(p.name||'').toLowerCase());if(lot)selectLot(lot.id)})}}).addTo(referenceGroup)}}catch(e){console.warn('Mapa de referencia no disponible',e)}
  const drawControl=new L.Control.Draw({edit:{featureGroup:S.drawn},draw:{polyline:false,circle:false,circlemarker:false,marker:false,polygon:{allowIntersection:false,showArea:true},rectangle:{showArea:true}}});S.map.addControl(drawControl);
  S.map.on(L.Draw.Event.CREATED,e=>{S.drawn.clearLayers();S.drawn.addLayer(e.layer);addStats(e.layer)});S.map.on(L.Draw.Event.EDITED,e=>e.layers.eachLayer(addStats));
  savedGroup.on('click',e=>{const lotId=e.layer?.options?.lotId;if(!lotId)return;selectLot(lotId);S.drawn.clearLayers();const copy=L.geoJSON(e.layer.toGeoJSON()).getLayers()[0];S.drawn.addLayer(copy);addStats(copy)});
  $('#mapLotSelect').onchange=e=>selectLot(e.target.value);
  $('#layerLots').onchange=e=>e.target.checked?S.map.addLayer(savedGroup):S.map.removeLayer(savedGroup);$('#layerReference').onchange=e=>e.target.checked?S.map.addLayer(referenceGroup):S.map.removeLayer(referenceGroup);$('#layerLabels').onchange=e=>e.target.checked?S.map.addLayer(labelGroup):S.map.removeLayer(labelGroup);
  $('#satelliteBtn').onclick=()=>{S.map.removeLayer(street);satellite.addTo(S.map)};$('#streetBtn').onclick=()=>{S.map.removeLayer(satellite);street.addTo(S.map)};
  $('#saveGeometry').onclick=saveGeometry;$('#clearDrawingBtn').onclick=()=>{S.drawn.clearLayers();$('#geometryStats').innerHTML='<span>Superficie</span><strong>Sin geometría</strong><span>Perímetro</span><strong>—</strong>';$('#gisMessage').textContent='Dibujo eliminado.'};
  $('#fitAllBtn').onclick=()=>{const bounds=L.latLngBounds([]);[savedGroup,referenceGroup].forEach(g=>g.eachLayer(l=>{if(l.getBounds)bounds.extend(l.getBounds())}));bounds.isValid()?S.map.fitBounds(bounds.pad(.08)):S.map.setView(center,15)};
  $('#gisFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const text=await file.text();let geo;if(file.name.toLowerCase().endsWith('.kml')){const xml=new DOMParser().parseFromString(text,'text/xml');geo=toGeoJSON.kml(xml)}else geo=JSON.parse(text);const imported=L.geoJSON(geo,{style:{color:'#1d6fa5',weight:3,fillColor:'#5fb4df',fillOpacity:.25}}),layers=[];imported.eachLayer(l=>{if(l.toGeoJSON&&['Polygon','MultiPolygon'].includes(l.toGeoJSON().geometry?.type))layers.push(l)});if(!layers.length)throw new Error('El archivo no contiene polígonos compatibles.');S.drawn.clearLayers();const chosen=layers[0];S.drawn.addLayer(chosen);addStats(chosen);S.map.fitBounds(chosen.getBounds().pad(.12));$('#gisMessage').textContent=`Importado: ${file.name}` }catch(err){alert(`No se pudo importar el archivo: ${err.message}`)}finally{e.target.value=''}};
  bindCardActions();setTimeout(()=>$('#fitAllBtn')?.click(),300)
}
async function saveGeometry(){const lotId=$('#mapLotSelect').value||S.selectedLotId,layer=S.drawn.getLayers()[0];if(!lotId)return alert('Seleccione un lote.');if(!layer)return alert('Dibuje un polígono con la herramienta del mapa.');const center=layer.getBounds().getCenter(),row={company_id:S.companyId,lot_id:lotId,geojson:layer.toGeoJSON(),center_lat:center.lat,center_lng:center.lng,updated_by:S.session.user.id,updated_at:new Date().toISOString()};const {error}=await sb.from('lot_geometries').upsert(row,{onConflict:'lot_id'});if(error)return alert(error.message);try{const area=turf.area(layer.toGeoJSON())/10000;await sb.from('lots').update({hectares:Number(area.toFixed(4))}).eq('id',lotId)}catch(e){console.warn(e)}await loadData();alert('Geometría guardada y superficie actualizada.');render()}

  return {
    renderPage: mapPage,
    initMap
  };
}
