export function createResourcesModule({ state, supabase, escapeHtml, openModal, loadData, render }) {
  const money=v=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(v||0));
  const number=(v,d=0)=>new Intl.NumberFormat('es-AR',{minimumFractionDigits:d,maximumFractionDigits:d}).format(Number(v||0));
  const today=()=>new Date().toISOString().slice(0,10);
  const byId=(rows,id)=>rows.find(x=>String(x.id)===String(id));

  function renderPage(){
    const equipment=state.equipment||[], fuel=state.fuelEntries||[], maintenance=state.maintenanceEntries||[], people=state.personnel||[], labor=state.laborEntries||[];
    const fuelLiters=fuel.reduce((s,x)=>s+Number(x.liters||0),0), fuelCost=fuel.reduce((s,x)=>s+Number(x.total_cost||0),0);
    const maintenanceCost=maintenance.reduce((s,x)=>s+Number(x.cost||0),0), laborCost=labor.reduce((s,x)=>s+Number(x.total_cost||0),0);
    const activeEquipment=equipment.filter(x=>x.status!=='Fuera de servicio').length;
    const nextMaintenance=maintenance.filter(x=>x.next_service_date&&x.next_service_date>=today()).sort((a,b)=>a.next_service_date.localeCompare(b.next_service_date))[0];
    const equipmentRows=equipment.map(x=>`<tr><td><b>${escapeHtml(x.name)}</b><small>${escapeHtml(x.category||'Equipo')}</small></td><td>${escapeHtml(x.brand||'—')} ${escapeHtml(x.model||'')}</td><td>${number(x.current_hours,1)} h</td><td><span class="pill">${escapeHtml(x.status||'Activo')}</span></td><td>${x.next_service_hours?`${number(x.next_service_hours,0)} h`:'—'}</td><td><button class="secondary editEquipment" data-id="${x.id}">Editar</button></td></tr>`).join('');
    const fuelRows=fuel.slice().sort((a,b)=>String(b.entry_date).localeCompare(String(a.entry_date))).slice(0,12).map(x=>{const eq=byId(equipment,x.equipment_id);return `<tr><td>${escapeHtml(x.entry_date||'—')}</td><td>${escapeHtml(eq?.name||'Sin equipo')}</td><td>${number(x.liters,1)} L</td><td>${money(x.price_per_liter)}</td><td>${money(x.total_cost)}</td><td>${number(x.hour_meter,1)} h</td></tr>`}).join('');
    const peopleRows=people.map(p=>`<tr><td><b>${escapeHtml(p.full_name)}</b><small>${escapeHtml(p.role||'Operario')}</small></td><td>${escapeHtml(p.phone||'—')}</td><td>${money(p.hourly_rate)}/h</td><td><span class="pill">${escapeHtml(p.status||'Activo')}</span></td><td><button class="secondary editPerson" data-id="${p.id}">Editar</button></td></tr>`).join('');
    return `<div class="page-head"><div><p class="eyebrow">RECURSOS OPERATIVOS · 10.1.0</p><h2>Maquinaria, combustible y personal</h2><p class="muted">Control de equipos, cargas de gasoil, mantenimiento y horas de trabajo.</p></div><div class="actions"><button class="secondary newFuel">+ Carga de gasoil</button><button class="secondary newMaintenance">+ Mantenimiento</button><button class="secondary newPerson">+ Personal</button><button class="primary newEquipment">+ Equipo</button></div></div>
      <div class="metrics resource-metrics"><div class="metric"><span>Equipos activos</span><b>${activeEquipment}</b><small>${equipment.length} registrados</small></div><div class="metric"><span>Combustible</span><b>${number(fuelLiters,1)} L</b><small>${money(fuelCost)}</small></div><div class="metric"><span>Mantenimiento</span><b>${money(maintenanceCost)}</b><small>${maintenance.length} intervenciones</small></div><div class="metric"><span>Mano de obra</span><b>${money(laborCost)}</b><small>${number(labor.reduce((s,x)=>s+Number(x.hours||0),0),1)} horas</small></div><div class="metric"><span>Personal activo</span><b>${people.filter(x=>x.status!=='Inactivo').length}</b><small>${people.length} registrados</small></div><div class="metric"><span>Próximo servicio</span><b>${nextMaintenance?escapeHtml(nextMaintenance.next_service_date):'Sin programar'}</b><small>${nextMaintenance?escapeHtml(byId(equipment,nextMaintenance.equipment_id)?.name||'Equipo'):'—'}</small></div></div>
      <div class="resource-grid"><div class="panel"><div class="panel-title"><div><h3>Parque de maquinaria</h3><p class="muted">Horas, estado y próximos servicios.</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Equipo</th><th>Marca / modelo</th><th>Horas</th><th>Estado</th><th>Próximo service</th><th></th></tr></thead><tbody>${equipmentRows||'<tr><td colspan="6" class="empty">Todavía no hay equipos registrados.</td></tr>'}</tbody></table></div></div>
      <div class="panel"><div class="panel-title"><div><h3>Últimas cargas de gasoil</h3><p class="muted">Consumo y costo por equipo.</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Fecha</th><th>Equipo</th><th>Litros</th><th>$/L</th><th>Total</th><th>Horómetro</th></tr></thead><tbody>${fuelRows||'<tr><td colspan="6" class="empty">Todavía no hay cargas registradas.</td></tr>'}</tbody></table></div></div></div>
      <div class="panel"><div class="panel-title"><div><h3>Personal operativo</h3><p class="muted">Tarifas horarias y disponibilidad.</p></div><button class="secondary newLabor">+ Registrar horas</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Nombre</th><th>Teléfono</th><th>Tarifa</th><th>Estado</th><th></th></tr></thead><tbody>${peopleRows||'<tr><td colspan="5" class="empty">Todavía no hay personal registrado.</td></tr>'}</tbody></table></div></div>`;
  }

  function equipmentModal(seed={}){openModal(`<p class="eyebrow">PARQUE DE MAQUINARIA</p><h2>${seed.id?'Editar equipo':'Nuevo equipo'}</h2><form id="equipmentForm"><input type="hidden" name="id" value="${seed.id||''}"><div class="form-grid"><label>Nombre<input name="name" value="${escapeHtml(seed.name||'')}" required></label><label>Categoría<select name="category">${['Tractor','Segadora','Rastrillo','Rotoenfardadora','Camión','Semirremolque','Pulverizador','Otro'].map(v=>`<option ${seed.category===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Marca<input name="brand" value="${escapeHtml(seed.brand||'')}"></label><label>Modelo<input name="model" value="${escapeHtml(seed.model||'')}"></label><label>Patente / Serie<input name="serial_number" value="${escapeHtml(seed.serial_number||'')}"></label><label>Horas actuales<input name="current_hours" type="number" step="0.1" value="${seed.current_hours||0}"></label><label>Próximo service (horas)<input name="next_service_hours" type="number" step="1" value="${seed.next_service_hours||0}"></label><label>Estado<select name="status">${['Activo','En mantenimiento','Fuera de servicio'].map(v=>`<option ${seed.status===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="wide">Observaciones<textarea name="notes">${escapeHtml(seed.notes||'')}</textarea></label></div><button class="primary">Guardar equipo</button><p id="resourceMsg" class="error hidden"></p></form>`);document.querySelector('#equipmentForm').onsubmit=saveEquipment;}
  async function saveEquipment(e){e.preventDefault();const f=new FormData(e.target),id=f.get('id'),row={company_id:state.companyId,name:f.get('name'),category:f.get('category'),brand:f.get('brand'),model:f.get('model'),serial_number:f.get('serial_number'),current_hours:Number(f.get('current_hours')||0),next_service_hours:Number(f.get('next_service_hours')||0),status:f.get('status'),notes:f.get('notes')};const r=id?await supabase.from('equipment').update(row).eq('id',id):await supabase.from('equipment').insert(row);if(r.error)return showError(r.error);closeAndReload();}
  function fuelModal(){const opts=(state.equipment||[]).map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join('');openModal(`<p class="eyebrow">COMBUSTIBLE</p><h2>Registrar carga de gasoil</h2><form id="fuelForm"><div class="form-grid"><label>Fecha<input name="entry_date" type="date" value="${today()}" required></label><label>Equipo<select name="equipment_id" required>${opts}</select></label><label>Litros<input name="liters" type="number" min="0.01" step="0.1" required></label><label>Precio por litro<input name="price_per_liter" type="number" min="0" step="0.01" required></label><label>Horómetro<input name="hour_meter" type="number" min="0" step="0.1"></label><label>Proveedor<input name="supplier"></label><label class="wide">Observaciones<textarea name="notes"></textarea></label></div><button class="primary">Guardar carga</button><p id="resourceMsg" class="error hidden"></p></form>`);document.querySelector('#fuelForm').onsubmit=saveFuel;}
  async function saveFuel(e){e.preventDefault();const f=new FormData(e.target),liters=Number(f.get('liters')||0),price=Number(f.get('price_per_liter')||0),row={company_id:state.companyId,equipment_id:f.get('equipment_id'),entry_date:f.get('entry_date'),liters,price_per_liter:price,total_cost:liters*price,hour_meter:Number(f.get('hour_meter')||0),supplier:f.get('supplier'),notes:f.get('notes')};const r=await supabase.from('fuel_entries').insert(row);if(r.error)return showError(r.error);closeAndReload();}
  function maintenanceModal(){const opts=(state.equipment||[]).map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join('');openModal(`<p class="eyebrow">MANTENIMIENTO</p><h2>Registrar intervención</h2><form id="maintenanceForm"><div class="form-grid"><label>Fecha<input name="service_date" type="date" value="${today()}" required></label><label>Equipo<select name="equipment_id" required>${opts}</select></label><label>Tipo<select name="service_type"><option>Preventivo</option><option>Correctivo</option><option>Reparación</option><option>Neumáticos</option><option>Lubricación</option></select></label><label>Costo<input name="cost" type="number" min="0" step="1"></label><label>Horómetro<input name="hour_meter" type="number" min="0" step="0.1"></label><label>Próximo service<input name="next_service_date" type="date"></label><label>Próximo service (horas)<input name="next_service_hours" type="number" min="0" step="1"></label><label>Proveedor / taller<input name="provider"></label><label class="wide">Detalle<textarea name="description" required></textarea></label></div><button class="primary">Guardar mantenimiento</button><p id="resourceMsg" class="error hidden"></p></form>`);document.querySelector('#maintenanceForm').onsubmit=saveMaintenance;}
  async function saveMaintenance(e){e.preventDefault();const f=new FormData(e.target),row={company_id:state.companyId,equipment_id:f.get('equipment_id'),service_date:f.get('service_date'),service_type:f.get('service_type'),description:f.get('description'),cost:Number(f.get('cost')||0),hour_meter:Number(f.get('hour_meter')||0),next_service_date:f.get('next_service_date')||null,next_service_hours:Number(f.get('next_service_hours')||0),provider:f.get('provider')};const r=await supabase.from('maintenance_entries').insert(row);if(r.error)return showError(r.error);closeAndReload();}
  function personModal(seed={}){openModal(`<p class="eyebrow">PERSONAL</p><h2>${seed.id?'Editar persona':'Nueva persona'}</h2><form id="personForm"><input type="hidden" name="id" value="${seed.id||''}"><div class="form-grid"><label>Nombre completo<input name="full_name" value="${escapeHtml(seed.full_name||'')}" required></label><label>Función<input name="role" value="${escapeHtml(seed.role||'Operario')}"></label><label>Teléfono<input name="phone" value="${escapeHtml(seed.phone||'')}"></label><label>Tarifa por hora<input name="hourly_rate" type="number" min="0" step="1" value="${seed.hourly_rate||0}"></label><label>Estado<select name="status"><option ${seed.status==='Activo'?'selected':''}>Activo</option><option ${seed.status==='Inactivo'?'selected':''}>Inactivo</option></select></label><label class="wide">Observaciones<textarea name="notes">${escapeHtml(seed.notes||'')}</textarea></label></div><button class="primary">Guardar personal</button><p id="resourceMsg" class="error hidden"></p></form>`);document.querySelector('#personForm').onsubmit=savePerson;}
  async function savePerson(e){e.preventDefault();const f=new FormData(e.target),id=f.get('id'),row={company_id:state.companyId,full_name:f.get('full_name'),role:f.get('role'),phone:f.get('phone'),hourly_rate:Number(f.get('hourly_rate')||0),status:f.get('status'),notes:f.get('notes')};const r=id?await supabase.from('personnel').update(row).eq('id',id):await supabase.from('personnel').insert(row);if(r.error)return showError(r.error);closeAndReload();}
  function laborModal(){const people=(state.personnel||[]).map(x=>`<option value="${x.id}">${escapeHtml(x.full_name)}</option>`).join(''), lots=(state.lots||[]).map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join('');openModal(`<p class="eyebrow">MANO DE OBRA</p><h2>Registrar horas trabajadas</h2><form id="laborForm"><div class="form-grid"><label>Fecha<input name="work_date" type="date" value="${today()}" required></label><label>Persona<select name="personnel_id" required>${people}</select></label><label>Lote<select name="lot_id"><option value="">Sin lote</option>${lots}</select></label><label>Actividad<input name="activity" placeholder="Ej. Corte, riego, mantenimiento" required></label><label>Horas<input name="hours" type="number" min="0.1" step="0.1" required></label><label>Tarifa por hora<input name="hourly_rate" type="number" min="0" step="1"></label><label class="wide">Observaciones<textarea name="notes"></textarea></label></div><button class="primary">Guardar horas</button><p id="resourceMsg" class="error hidden"></p></form>`);document.querySelector('#laborForm').onsubmit=saveLabor;}
  async function saveLabor(e){e.preventDefault();const f=new FormData(e.target),person=byId(state.personnel||[],f.get('personnel_id')),hours=Number(f.get('hours')||0),rate=Number(f.get('hourly_rate')||person?.hourly_rate||0),row={company_id:state.companyId,personnel_id:f.get('personnel_id'),lot_id:f.get('lot_id')||null,work_date:f.get('work_date'),activity:f.get('activity'),hours,hourly_rate:rate,total_cost:hours*rate,notes:f.get('notes')};const r=await supabase.from('labor_entries').insert(row);if(r.error)return showError(r.error);closeAndReload();}
  function showError(error){const m=document.querySelector('#resourceMsg');if(m){m.textContent=error.message||String(error);m.classList.remove('hidden');}}
  async function closeAndReload(){document.querySelector('#modalRoot').innerHTML='';await loadData();render();}
  function bind(){document.querySelectorAll('.newEquipment').forEach(b=>b.onclick=()=>equipmentModal());document.querySelectorAll('.newFuel').forEach(b=>b.onclick=fuelModal);document.querySelectorAll('.newMaintenance').forEach(b=>b.onclick=maintenanceModal);document.querySelectorAll('.newPerson').forEach(b=>b.onclick=()=>personModal());document.querySelectorAll('.newLabor').forEach(b=>b.onclick=laborModal);document.querySelectorAll('.editEquipment').forEach(b=>b.onclick=()=>equipmentModal(byId(state.equipment||[],b.dataset.id)||{}));document.querySelectorAll('.editPerson').forEach(b=>b.onclick=()=>personModal(byId(state.personnel||[],b.dataset.id)||{}));}
  return {renderPage,bind};
}
