function cutMeta(cut){try{const n=String(cut.notes||'');return n.startsWith('LMOS_CUT:')?JSON.parse(n.slice(9)):{};}catch{return {}}}
function normalizeCut(cut){const m=cutMeta(cut),rolls=Number(cut.bales||cut.rolls||0),kg=Number(cut.total_kg||0);return {...cut,...m,rolls,kg,weight:rolls?kg/rolls:Number(m.weight||500),batch_code:m.batch_code||`CORTE-${String(cut.id||'').slice(0,6).toUpperCase()}`}}
export function createSalesModule({state,supabase,escapeHtml,openModal,loadData,render}){
 const money=v=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(v||0));
 const number=(v,d=1)=>new Intl.NumberFormat('es-AR',{minimumFractionDigits:d,maximumFractionDigits:d}).format(Number(v||0));
 const today=()=>new Date().toISOString().slice(0,10), byId=(a,id)=>a.find(x=>String(x.id)===String(id));
 const cuts=()=>state.cuts.map(normalizeCut);
 const stockOf=cut=>{const movements=(state.stockMovements||[]).filter(m=>m.cut_id===cut.id);return Math.max(0,cut.rolls+movements.reduce((s,m)=>s+(m.movement_type==='Ingreso'?Number(m.quantity||0):-Number(m.quantity||0)),0));};
 const sales=()=>[...(state.salesOrders||[])].sort((a,b)=>String(b.sale_date).localeCompare(String(a.sale_date)));
 function renderPage(){const rows=sales(),total=rows.reduce((s,x)=>s+Number(x.total_amount||0),0),paid=rows.reduce((s,x)=>s+Number(x.paid_amount||0),0),balance=total-paid,overdue=rows.filter(x=>x.due_date&&Number(x.total_amount)>Number(x.paid_amount)&&x.due_date<today()),clientNames=[...new Set(rows.map(x=>x.client_name).filter(Boolean))];
 return `<div class="page-head"><div><p class="eyebrow">GESTIÓN COMERCIAL · 11.0.0</p><h2>Ventas, remitos y cobranzas</h2><p class="muted">Cuenta corriente por cliente, salida automática de stock y registro financiero de cada cobro.</p></div><div class="actions"><button class="secondary exportSales">Exportar CSV</button><button class="primary newSale">+ Nueva venta</button></div></div>
 <div class="metrics"><div class="metric"><span>Facturado</span><b>${money(total)}</b><small>${rows.length} operaciones</small></div><div class="metric"><span>Cobrado</span><b>${money(paid)}</b><small>${total?number(paid/total*100,1):'0,0'}% del total</small></div><div class="metric"><span>Saldo pendiente</span><b>${money(balance)}</b><small>${rows.filter(x=>Number(x.total_amount)>Number(x.paid_amount)).length} cuentas abiertas</small></div><div class="metric"><span>Vencidas</span><b>${overdue.length}</b><small>${money(overdue.reduce((s,x)=>s+Number(x.total_amount)-Number(x.paid_amount),0))}</small></div></div>
 <div class="grid2"><div class="panel"><div class="panel-title"><div><p class="eyebrow">CUENTAS CORRIENTES</p><h3>Saldos por cliente</h3></div><span class="pill">${clientNames.length} clientes</span></div>${clientNames.length?clientNames.map(name=>{const a=rows.filter(x=>x.client_name===name),t=a.reduce((s,x)=>s+Number(x.total_amount),0),p=a.reduce((s,x)=>s+Number(x.paid_amount),0);return `<div class="row"><div><b>${escapeHtml(name)}</b><small>${a.length} operaciones</small></div><div style="text-align:right"><b>${money(t-p)}</b><small>saldo</small></div></div>`}).join(''):'<div class="empty">Todavía no hay ventas registradas.</div>'}</div>
 <div class="panel"><div class="panel-title"><div><p class="eyebrow">ALERTAS</p><h3>Vencimientos</h3></div><span class="pill">${overdue.length}</span></div>${overdue.length?overdue.slice(0,8).map(x=>`<div class="row"><div><b>${escapeHtml(x.client_name)}</b><small>Venció ${escapeHtml(x.due_date)} · ${escapeHtml(x.invoice_number||x.delivery_note||'Sin comprobante')}</small></div><b>${money(Number(x.total_amount)-Number(x.paid_amount))}</b></div>`).join(''):'<div class="status">No hay cuentas vencidas.</div>'}</div></div>
 <div class="panel"><div class="panel-title"><div><h3>Operaciones comerciales</h3><small>Ventas vinculadas con stock, comprobantes y cobranzas.</small></div><span class="pill">${rows.length}</span></div>${rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Fecha</th><th>Cliente</th><th>Comprobante</th><th>Total</th><th>Cobrado</th><th>Saldo</th><th>Estado</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${escapeHtml(x.sale_date)}</td><td><b>${escapeHtml(x.client_name)}</b><small>${escapeHtml(x.payment_terms||'')}</small></td><td>${escapeHtml(x.invoice_number||x.delivery_note||'—')}</td><td>${money(x.total_amount)}</td><td>${money(x.paid_amount)}</td><td class="${Number(x.total_amount)>Number(x.paid_amount)?'negative':'positive'}">${money(Number(x.total_amount)-Number(x.paid_amount))}</td><td><span class="pill">${escapeHtml(x.status)}</span></td><td>${Number(x.total_amount)>Number(x.paid_amount)?`<button class="secondary collectSale" data-id="${x.id}">Cobrar</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><b>No hay operaciones comerciales.</b><p>Registrá una venta para descontar stock y abrir la cuenta corriente.</p></div>'}</div>`}
 function saleModal(){const available=cuts().filter(c=>stockOf(c)>0),clientOptions=(state.clients||[]).map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('');openModal(`<p class="eyebrow">NUEVA VENTA</p><h2>Venta de rollos de alfalfa</h2><form id="saleForm"><div class="form-grid"><label>Fecha<input name="sale_date" type="date" value="${today()}" required></label><label>Cliente<select name="client_id" required><option value="">Seleccionar</option>${clientOptions}</select></label><label>Partida<select name="cut_id" required><option value="">Seleccionar</option>${available.map(c=>`<option value="${c.id}">${escapeHtml(c.batch_code)} · ${stockOf(c)} rollos</option>`).join('')}</select></label><label>Cantidad de rollos<input name="quantity" type="number" min="1" value="1" required></label><label>Modalidad<select name="price_mode"><option>Por rollo</option><option>Por tonelada</option></select></label><label>Precio por rollo (ARS)<input name="unit_price" type="number" min="0" step="1" value="0"></label><label>Precio por tonelada (ARS)<input name="ton_price" type="number" min="0" step="1" value="0"></label><label>Condición<select name="payment_terms"><option>Contado</option><option>7 días</option><option>15 días</option><option>30 días</option><option>60 días</option><option>Cuenta corriente</option></select></label><label>Vencimiento<input name="due_date" type="date"></label><label>Factura<input name="invoice_number"></label><label>Remito<input name="delivery_note"></label><label>Cobro inicial (ARS)<input name="initial_payment" type="number" min="0" step="1" value="0"></label><label>Medio de pago<select name="payment_method"><option>Transferencia</option><option>Efectivo</option><option>Cheque</option><option>Depósito</option><option>Otro</option></select></label><label class="wide">Observaciones<textarea name="notes"></textarea></label></div><div id="salePreview" class="status">Completá partida, cantidad y precio.</div><button class="primary">Guardar venta</button><p id="saleMsg" class="error hidden"></p></form>`);const form=document.querySelector('#saleForm');const preview=()=>{const f=new FormData(form),cut=byId(available,f.get('cut_id')),q=Number(f.get('quantity')||0),mode=f.get('price_mode'),total=mode==='Por tonelada'?(q*Number(cut?.weight||500)/1000)*Number(f.get('ton_price')||0):q*Number(f.get('unit_price')||0);document.querySelector('#salePreview').innerHTML=`<b>Resumen:</b> ${q} rollos · ${number(q*Number(cut?.weight||500)/1000,1)} t · ${money(total)}${cut?` · quedan ${Math.max(0,stockOf(cut)-q)} rollos`:''}`};form.oninput=preview;form.onsubmit=saveSale;preview();}
 async function saveSale(e){e.preventDefault();const f=new FormData(e.target),msg=document.querySelector('#saleMsg'),client=byId(state.clients||[],f.get('client_id')),cut=byId(cuts(),f.get('cut_id'));try{if(!client||!cut)throw new Error('Seleccione cliente y partida.');const quantity=Number(f.get('quantity')||0);if(quantity>stockOf(cut))throw new Error('La venta supera el stock disponible.');const {error}=await supabase.rpc('register_alfalfa_sale',{p_company_id:state.companyId,p_client_id:client.id,p_client_name:client.name,p_cut_id:cut.id,p_sale_date:f.get('sale_date'),p_due_date:f.get('due_date')||null,p_payment_terms:f.get('payment_terms'),p_quantity:quantity,p_weight_per_roll:Number(cut.weight||500),p_price_mode:f.get('price_mode'),p_unit_price:Number(f.get('unit_price')||0),p_ton_price:Number(f.get('ton_price')||0),p_invoice_number:f.get('invoice_number')||'',p_delivery_note:f.get('delivery_note')||'',p_initial_payment:Number(f.get('initial_payment')||0),p_payment_method:f.get('payment_method'),p_notes:f.get('notes')||''});if(error)throw error;await closeReload();}catch(err){msg.textContent=err.message||String(err);msg.classList.remove('hidden')}}
 function paymentModal(id){const sale=byId(sales(),id),balance=Number(sale.total_amount)-Number(sale.paid_amount);openModal(`<p class="eyebrow">COBRANZA</p><h2>${escapeHtml(sale.client_name)}</h2><p class="status">Saldo pendiente: <b>${money(balance)}</b></p><form id="paymentForm"><div class="form-grid"><label>Fecha<input name="payment_date" type="date" value="${today()}" required></label><label>Monto (ARS)<input name="amount" type="number" min="1" max="${balance}" value="${balance}" required></label><label>Medio<select name="payment_method"><option>Transferencia</option><option>Efectivo</option><option>Cheque</option><option>Depósito</option><option>Otro</option></select></label><label>Referencia<input name="reference" placeholder="N° transferencia o cheque"></label><label class="wide">Observaciones<textarea name="notes"></textarea></label></div><button class="primary">Registrar cobro</button><p id="paymentMsg" class="error hidden"></p></form>`);document.querySelector('#paymentForm').onsubmit=e=>savePayment(e,id);}
 async function savePayment(e,id){e.preventDefault();const f=new FormData(e.target),m=document.querySelector('#paymentMsg');const {error}=await supabase.rpc('register_sale_payment',{p_sale_id:id,p_payment_date:f.get('payment_date'),p_amount:Number(f.get('amount')||0),p_payment_method:f.get('payment_method'),p_reference:f.get('reference')||'',p_notes:f.get('notes')||''});if(error){m.textContent=error.message;m.classList.remove('hidden');return}await closeReload();}
 function exportCsv(){const header=['Fecha','Cliente','Factura','Remito','Total ARS','Cobrado ARS','Saldo ARS','Estado'];const data=sales().map(x=>[x.sale_date,x.client_name,x.invoice_number||'',x.delivery_note||'',x.total_amount,x.paid_amount,Number(x.total_amount)-Number(x.paid_amount),x.status]);const csv=[header,...data].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download=`ventas-${today()}.csv`;a.click();URL.revokeObjectURL(a.href)}
 async function closeReload(){document.querySelector('#modalRoot').innerHTML='';await loadData();render()}
 function bind(){document.querySelectorAll('.newSale').forEach(b=>b.onclick=saleModal);document.querySelectorAll('.collectSale').forEach(b=>b.onclick=()=>paymentModal(b.dataset.id));document.querySelectorAll('.exportSales').forEach(b=>b.onclick=exportCsv)}
 return {renderPage,bind};
}
