export function createCrmModule({state,supabase,escapeHtml,openModal,loadData,render}){
 const money=v=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(v||0));
 const num=(v,d=0)=>new Intl.NumberFormat('es-AR',{minimumFractionDigits:d,maximumFractionDigits:d}).format(Number(v||0));
 const clientName=id=>(state.clients||[]).find(x=>x.id===id)?.trade_name||(state.clients||[]).find(x=>x.id===id)?.name||'Cliente';
 const stages=['Nueva','Contactado','Cotización','Negociación','Ganada','Perdida'];
 function renderPage(){
  const clients=state.clients||[], contacts=state.crmContacts||[], est=state.crmEstablishments||[], opps=state.crmOpportunities||[], acts=state.crmActivities||[];
  const active=clients.filter(x=>(x.status||'Activo')==='Activo').length, prospects=clients.filter(x=>x.status==='Prospecto').length;
  const hectares=est.reduce((s,x)=>s+Number(x.total_hectares||0),0);
  const pipeline=opps.filter(x=>!['Ganada','Perdida'].includes(x.stage)).reduce((s,x)=>s+Number(x.estimated_amount||0)*Number(x.probability||0)/100,0);
  const balance=clients.reduce((s,x)=>s+Number(x.current_balance||0),0);
  return `<div class="page-head"><div><p class="eyebrow">CRM PROFESIONAL · 25.0.0</p><h2>Clientes y oportunidades</h2><p class="muted">Gestión comercial integrada con establecimientos, contactos, tareas y ventas.</p></div><div class="actions"><button class="secondary newOpportunity">+ Oportunidad</button><button class="primary newCrmClient">+ Nuevo cliente</button></div></div>
  <div class="metrics"><div class="metric"><span>Clientes activos</span><b>${active}</b><small>${prospects} prospectos</small></div><div class="metric"><span>Hectáreas vinculadas</span><b>${num(hectares)} ha</b><small>${est.length} establecimientos</small></div><div class="metric"><span>Pipeline ponderado</span><b>${money(pipeline)}</b><small>${opps.filter(x=>!['Ganada','Perdida'].includes(x.stage)).length} oportunidades abiertas</small></div><div class="metric"><span>Saldo a cobrar</span><b>${money(balance)}</b><small>cuentas corrientes CRM</small></div></div>
  <div class="grid2"><div class="panel"><div class="panel-title"><div><h3>Clientes</h3><small>Datos fiscales, comerciales y productivos.</small></div><input id="crmSearch" placeholder="Buscar cliente o localidad" style="max-width:230px"></div><div id="crmClientList">${clientRows(clients)}</div></div>
  <div class="panel"><div class="panel-title"><div><h3>Pipeline comercial</h3><small>Oportunidades por etapa.</small></div><span class="pill">${opps.length}</span></div>${opps.length?opps.sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,10).map(o=>`<div class="row"><div><b>${escapeHtml(o.title)}</b><small>${escapeHtml(clientName(o.client_id))} · ${escapeHtml(o.service_type||'Servicio')}</small></div><div style="text-align:right"><b>${money(o.estimated_amount)}</b><small>${escapeHtml(o.stage)} · ${num(o.probability)}%</small></div></div>`).join(''):'<div class="empty">No hay oportunidades registradas.</div>'}</div></div>
  <div class="grid2"><div class="panel"><div class="panel-title"><h3>Próximas actividades</h3><button class="secondary newActivity">+ Actividad</button></div>${acts.length?acts.filter(a=>!a.completed_at).sort((a,b)=>String(a.due_at||'9999').localeCompare(String(b.due_at||'9999'))).slice(0,8).map(a=>`<div class="row"><div><b>${escapeHtml(a.subject)}</b><small>${escapeHtml(clientName(a.client_id))} · ${escapeHtml(a.activity_type)}</small></div><span class="pill">${a.due_at?escapeHtml(String(a.due_at).slice(0,10)):'Sin fecha'}</span></div>`).join(''):'<div class="empty">No hay actividades pendientes.</div>'}</div>
  <div class="panel"><div class="panel-title"><h3>Red comercial</h3></div><div class="metrics" style="grid-template-columns:repeat(2,1fr)"><div class="metric"><span>Contactos</span><b>${contacts.length}</b></div><div class="metric"><span>Establecimientos</span><b>${est.length}</b></div></div></div></div>`;
 }
 function clientRows(rows){return rows.length?rows.map(c=>`<div class="row crm-client-row" data-search="${escapeHtml(`${c.name||''} ${c.trade_name||''} ${c.cuit||''} ${c.city||c.location||''}`.toLowerCase())}"><div><b>${escapeHtml(c.trade_name||c.name)}</b><small>${escapeHtml(c.name)}${c.cuit?` · CUIT ${escapeHtml(c.cuit)}`:''}<br>${escapeHtml([c.city||c.location,c.province].filter(Boolean).join(', '))}</small></div><div class="actions"><span class="pill">${escapeHtml(c.status||'Activo')}</span><button class="secondary editCrmClient" data-id="${c.id}">Editar</button><button class="secondary crmClientDetail" data-id="${c.id}">Ficha</button></div></div>`).join(''):'<div class="empty">Todavía no hay clientes cargados.</div>'}
 function clientModal(c={}){openModal(`<p class="eyebrow">CRM</p><h2>${c.id?'Editar cliente':'Nuevo cliente'}</h2><form id="crmClientForm"><input type="hidden" name="id" value="${escapeHtml(c.id||'')}"><div class="form-grid"><label>Razón social<input name="name" required value="${escapeHtml(c.name||'')}"></label><label>Nombre comercial<input name="trade_name" value="${escapeHtml(c.trade_name||'')}"></label><label>CUIT<input name="cuit" value="${escapeHtml(c.cuit||'')}"></label><label>Condición IVA<select name="vat_condition">${['','Responsable Inscripto','Monotributista','Exento','Consumidor Final'].map(x=>`<option ${x===(c.vat_condition||'')?'selected':''}>${x}</option>`).join('')}</select></label><label>Email<input type="email" name="email" value="${escapeHtml(c.email||'')}"></label><label>WhatsApp<input name="whatsapp" value="${escapeHtml(c.whatsapp||c.phone||'')}"></label><label>Localidad<input name="city" value="${escapeHtml(c.city||c.location||'')}"></label><label>Provincia<input name="province" value="${escapeHtml(c.province||'Córdoba')}"></label><label>Estado<select name="status">${['Activo','Prospecto','Inactivo','Bloqueado'].map(x=>`<option ${x===(c.status||'Activo')?'selected':''}>${x}</option>`).join('')}</select></label><label>Límite de crédito (ARS)<input type="number" name="credit_limit" value="${Number(c.credit_limit||0)}"></label><label>Forma de pago<input name="payment_terms" value="${escapeHtml(c.payment_terms||'')}"></label><label class="wide">Dirección<input name="address" value="${escapeHtml(c.address||'')}"></label><label class="wide">Notas<textarea name="notes">${escapeHtml(c.notes||'')}</textarea></label></div><button class="primary">Guardar cliente</button><p id="crmMsg" class="error hidden"></p></form>`);document.querySelector('#crmClientForm').onsubmit=saveClient;}
 async function saveClient(e){e.preventDefault();const f=new FormData(e.target),id=f.get('id'),row={company_id:state.companyId,name:f.get('name'),trade_name:f.get('trade_name')||null,cuit:f.get('cuit')||null,vat_condition:f.get('vat_condition')||null,email:f.get('email')||null,whatsapp:f.get('whatsapp')||null,phone:f.get('whatsapp')||null,city:f.get('city')||null,location:f.get('city')||null,province:f.get('province')||null,status:f.get('status'),credit_limit:Number(f.get('credit_limit')||0),payment_terms:f.get('payment_terms')||null,address:f.get('address')||null,notes:f.get('notes')||null,updated_at:new Date().toISOString()};const q=id?supabase.from('clients').update(row).eq('id',id):supabase.from('clients').insert(row);const {error}=await q;if(error){const m=document.querySelector('#crmMsg');m.textContent=error.message;m.classList.remove('hidden');return}await closeReload();}
 function opportunityModal(){const opts=(state.clients||[]).map(c=>`<option value="${c.id}">${escapeHtml(c.trade_name||c.name)}</option>`).join('');openModal(`<p class="eyebrow">PIPELINE</p><h2>Nueva oportunidad</h2><form id="crmOppForm"><div class="form-grid"><label>Cliente<select name="client_id" required><option value="">Seleccionar</option>${opts}</select></label><label>Título<input name="title" required></label><label>Servicio<input name="service_type" placeholder="Drone, fertilización, flete..."></label><label>Monto estimado (ARS)<input type="number" name="estimated_amount" min="0"></label><label>Probabilidad %<input type="number" name="probability" min="0" max="100" value="50"></label><label>Etapa<select name="stage">${stages.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Fecha esperada<input type="date" name="expected_date"></label><label class="wide">Notas<textarea name="notes"></textarea></label></div><button class="primary">Guardar oportunidad</button><p id="crmOppMsg" class="error hidden"></p></form>`);document.querySelector('#crmOppForm').onsubmit=saveOpportunity;}
 async function saveOpportunity(e){e.preventDefault();const f=new FormData(e.target),row={company_id:state.companyId,client_id:f.get('client_id'),title:f.get('title'),service_type:f.get('service_type')||null,estimated_amount:Number(f.get('estimated_amount')||0),probability:Number(f.get('probability')||0),stage:f.get('stage'),expected_date:f.get('expected_date')||null,notes:f.get('notes')||null};const {error}=await supabase.from('crm_opportunities').insert(row);if(error){const m=document.querySelector('#crmOppMsg');m.textContent=error.message;m.classList.remove('hidden');return}await closeReload();}
 function activityModal(){const opts=(state.clients||[]).map(c=>`<option value="${c.id}">${escapeHtml(c.trade_name||c.name)}</option>`).join('');openModal(`<p class="eyebrow">SEGUIMIENTO</p><h2>Nueva actividad</h2><form id="crmActForm"><div class="form-grid"><label>Cliente<select name="client_id" required><option value="">Seleccionar</option>${opts}</select></label><label>Tipo<select name="activity_type">${['Llamada','WhatsApp','Email','Visita','Tarea','Nota'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Asunto<input name="subject" required></label><label>Fecha prevista<input type="datetime-local" name="due_at"></label><label class="wide">Detalle<textarea name="detail"></textarea></label></div><button class="primary">Guardar actividad</button><p id="crmActMsg" class="error hidden"></p></form>`);document.querySelector('#crmActForm').onsubmit=saveActivity;}
 async function saveActivity(e){e.preventDefault();const f=new FormData(e.target),row={company_id:state.companyId,client_id:f.get('client_id'),activity_type:f.get('activity_type'),subject:f.get('subject'),due_at:f.get('due_at')||null,detail:f.get('detail')||null};const {error}=await supabase.from('crm_activities').insert(row);if(error){const m=document.querySelector('#crmActMsg');m.textContent=error.message;m.classList.remove('hidden');return}await closeReload();}
 function detailModal(id){const c=(state.clients||[]).find(x=>x.id===id), contacts=(state.crmContacts||[]).filter(x=>x.client_id===id), est=(state.crmEstablishments||[]).filter(x=>x.client_id===id), opp=(state.crmOpportunities||[]).filter(x=>x.client_id===id);openModal(`<p class="eyebrow">FICHA 360</p><h2>${escapeHtml(c?.trade_name||c?.name||'Cliente')}</h2><div class="metrics"><div class="metric"><span>Contactos</span><b>${contacts.length}</b></div><div class="metric"><span>Establecimientos</span><b>${est.length}</b></div><div class="metric"><span>Hectáreas</span><b>${num(est.reduce((s,x)=>s+Number(x.total_hectares||0),0))}</b></div><div class="metric"><span>Oportunidades</span><b>${opp.length}</b></div></div><div class="panel"><p><b>CUIT:</b> ${escapeHtml(c?.cuit||'—')}</p><p><b>Contacto:</b> ${escapeHtml(c?.whatsapp||c?.phone||'—')} · ${escapeHtml(c?.email||'—')}</p><p><b>Ubicación:</b> ${escapeHtml([c?.address,c?.city||c?.location,c?.province].filter(Boolean).join(', ')||'—')}</p><p><b>Condición comercial:</b> ${escapeHtml(c?.payment_terms||'Sin definir')} · límite ${money(c?.credit_limit)}</p><p><b>Notas:</b> ${escapeHtml(c?.notes||'—')}</p></div>`)}
 async function closeReload(){document.querySelector('#modalRoot').innerHTML='';await loadData();render();}
 function bind(){document.querySelectorAll('.newCrmClient').forEach(b=>b.onclick=()=>clientModal());document.querySelectorAll('.editCrmClient').forEach(b=>b.onclick=()=>clientModal((state.clients||[]).find(x=>x.id===b.dataset.id)||{}));document.querySelectorAll('.crmClientDetail').forEach(b=>b.onclick=()=>detailModal(b.dataset.id));document.querySelectorAll('.newOpportunity').forEach(b=>b.onclick=opportunityModal);document.querySelectorAll('.newActivity').forEach(b=>b.onclick=activityModal);const q=document.querySelector('#crmSearch');if(q)q.oninput=()=>{const term=q.value.toLowerCase();document.querySelectorAll('.crm-client-row').forEach(r=>r.classList.toggle('hidden',!r.dataset.search.includes(term)))}}
 return {renderPage,bind};
}
